### ISSUE TITLE
Fix support for node 8

### ISSUE THREAD

**Issue by mouhsinelonly** [medooze/media-server-node#10]
ubuntu 16.04
npm 5.4.2
node v8.6.0

`../src/media-server_wrap.cxx: In function ‘swig_module_info* SWIG_V8_GetModule(void*)’:
../src/media-server_wrap.cxx:12779:49: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
   v8::Local<v8::Value> moduleinfo = global_obj->GetHiddenValue(SWIGV8_STRING_NEW("swig_module_info_data"));
                                                 ^
medooze-media-server.target.mk:184: recipe for target 'Release/obj.target/medooze-media-server/src/media-server_wrap.o' failed
make: *** [Release/obj.target/medooze-media-server/src/media-server_wrap.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/usr/local/media-server-demo-node/node_modules/medooze-media-server/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-96-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-j" "4"
gyp ERR! cwd /usr/local/media-server-demo-node/node_modules/medooze-media-server
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.6.0 install: `node-gyp rebuild -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medooze-media-server@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by murillo128** [comment]
I think current version that I am using from swig does not support node 8. I will try updating it and check it it fixes the problems.

**Comment by murillo128** [comment]
Should be fixed in https://github.com/medooze/media-server-node/commit/15fb56a003275010bf451000a5e7da13a807c0ea
