### ISSUE TITLE
Add timers to outgoing ICE request for remote candidates to prevent server to server connection will fail when  we lost  stun binding request packet  

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#102]
I came to this when i have many server to server relay.

**Comment by notedit** [comment]
I have fixed this by create a timer to send binding request  multi times.

**Comment by notedit** [comment]
@murillo128  do you have any better idea for this?

**Comment by murillo128** [comment]
I was thinking something similar the other day. The only problem is that I would have to add one timer per remote ice candidate which would require some non-trivial changes.

I like the idea, but require a clean approach and probably a bit oc code refactor

**Comment by murillo128** [comment]
A new timer for retransmitting the ICE binding request has been implemented. You can control the timeout value in the `Endpoint` object.

Please, test it and let me know how it works for you.

**Comment by notedit** [comment]
Thanks,  will test it next weak.
