### ISSUE TITLE
Default media server capabilities

### ISSUE THREAD

**Issue by bakoushin** [medooze/media-server-node#104]
Is there a way to get all capabilities supported by the media server?

**Current situation**
At the moment, a developer must explicitly specify supported capabilities using the API. For example, capabilities are needed for these methods:  
* `Endpoint#createSPDManager`
* `MediaInfo.create`
* `MediaInfo#answer`

This is requiring a developer to do a research on which capabilities are supported by the media server.

**Suggestion**
Provide a static method of `MediaServer`, which will return a default object of capabilities supported by the media server. For example:
* `MediaServer.getVideoCapabilities()`
* `MediaServer.getAudioCapabilities()`

**Comment by murillo128** [comment]
Thanxs for the idea! I have added a `MediaServer.getDefaultCapabilities()` that returns current preferred ones:
```
	{
		audio : {
			codecs		: ["opus","pcmu","pcma"],
			extensions	: [
				"urn:ietf:params:rtp-hdrext:ssrc-audio-level",
				"urn:ietf:params:rtp-hdrext:sdes:mid",
				"urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id",
				"http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time"
			]
		},
		video : {
			codecs		: ["vp8","vp9","h264;packetization-mode=1","av1"],
			rtx		: true,
			rtcpfbs		: [
				{ "id": "goog-remb"},
				{ "id": "transport-cc"},
				{ "id": "ccm", "params": ["fir"]},
				{ "id": "nack"},
				{ "id": "nack", "params": ["pli"]}
			],
			extensions	: [
				"urn:3gpp:video-orientation",
				"http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
				"urn:ietf:params:rtp-hdrext:sdes:mid",
				"urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id",
				"urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id",
				"http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time"
			]
		}
	}
```

**Comment by bakoushin** [comment]
Thanks for implementing it! Should the new method be listed in `medooze-media-server.d.ts` as well?
