### ISSUE TITLE
Unable to record tracks on remote servers

### ISSUE THREAD

**Issue by beingmountain23** [medooze/media-server-node#105]
Hi @murillo128 
I have been using the Medooze Media Server package for my nodejs project.
It has been working fine when my recording initiator (client) and server are present on the same LAN. When I try to hit a remote server, acting as the media server, the Websocket connection is established with the exchange of offer and answer, an ICE candidate is also chosen for transmission, but on ending the recording the file size remains 1Kb, and no video or audio tracks are recorded.
I am using a Google Cloud VM instance to act as the remote server. The media server endpoint is the Google Cloud Instance's public IP, and the server has its own private IP.
All requests are sent to the public IP at port 8000, and forwarded to the private IP correctly, to create the answer and receive UDP packets, but the recording file dump is created without any video or audio content in it i.e. an empty file.
All paths from the Public IP to the Private IP are open in this scenario hence the Websocket Offer and Answer occurs successfully. I have exposed ports from 10000 to 55000 for the Media Server.
Yet the file dump created is empty.
The answer received by the client is shown below:
**ANSWER:**
v=0
o=- 1567668622493 1 IN IP4 127.0.0.1
s=semantic-sdp
c=IN IP4 0.0.0.0
t=0 0
a=ice-lite
a=msid-semantic: WMS *
a=group:BUNDLE 0 1
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=setup:passive
a=mid:0
a=sendrecv
a=ice-ufrag:cf01ba687a6fdfe0
a=ice-pwd:a8676c406ae16d1f53b1b9c0c8a01f5895405ce9e977d125
a=fingerprint:sha-256 A3:FB:6E:CE:E6:60:4A:EF:29:00:3E:FC:DD:A3:42:CC:82:82:14:8D:45:DD:B4:53:20:59:DE:A5:BD:E0:7A:4C
a=candidate:1 1 UDP 2130706431 34.93.161.175 50808 typ host
a=rtcp-mux
a=rtcp-rsize
m=video 9 UDP/TLS/RTP/SAVPF 98 99 100 101 102 122 125 107 124 120 123 119
a=rtpmap:98 VP9/90000
a=rtpmap:99 rtx/90000
a=rtpmap:100 VP9/90000
a=rtpmap:101 rtx/90000
a=rtpmap:102 H264/90000
a=rtpmap:122 rtx/90000
a=rtpmap:125 H264/90000
a=rtpmap:107 rtx/90000
a=rtpmap:124 H264/90000
a=rtpmap:120 rtx/90000
a=rtpmap:123 H264/90000
a=rtpmap:119 rtx/90000
a=fmtp:99 apt=98
a=fmtp:98 profile-id=0
a=fmtp:101 apt=100
a=fmtp:100 profile-id=2
a=fmtp:122 apt=102
a=fmtp:102 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
a=fmtp:107 apt=125
a=fmtp:125 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
a=fmtp:120 apt=124
a=fmtp:124 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=4d0032
a=fmtp:119 apt=123
a=fmtp:123 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=640032
a=rtcp-fb:98 transport-cc 
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack 
a=rtcp-fb:98 nack pli
a=rtcp-fb:100 transport-cc 
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack 
a=rtcp-fb:100 nack pli
a=rtcp-fb:102 transport-cc 
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli
a=rtcp-fb:125 transport-cc 
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli
a=rtcp-fb:124 transport-cc 
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack 
a=rtcp-fb:124 nack pli
a=rtcp-fb:123 transport-cc 
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack 
a=rtcp-fb:123 nack pli
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=setup:passive
a=mid:1
a=sendrecv
a=ice-ufrag:cf01ba687a6fdfe0
a=ice-pwd:a8676c406ae16d1f53b1b9c0c8a01f5895405ce9e977d125
a=fingerprint:sha-256 A3:FB:6E:CE:E6:60:4A:EF:29:00:3E:FC:DD:A3:42:CC:82:82:14:8D:45:DD:B4:53:20:59:DE:A5:BD:E0:7A:4C
a=candidate:1 1 UDP 2130706431 34.93.161.175 50808 typ host
a=ssrc:279434614 cname:708efb21-d1eb-483f-813a-ac0cd62cc24b
a=ssrc:279434614 msid:708efb21-d1eb-483f-813a-ac0cd62cc24b video0
a=ssrc:362380999 cname:708efb21-d1eb-483f-813a-ac0cd62cc24b
a=ssrc:362380999 msid:708efb21-d1eb-483f-813a-ac0cd62cc24b video0
a=ssrc:961710332 cname:708efb21-d1eb-483f-813a-ac0cd62cc24b
a=ssrc:961710332 msid:708efb21-d1eb-483f-813a-ac0cd62cc24b video0
a=ssrc-group:FID 279434614 362380999
a=ssrc-group:FEC-FR 279434614 961710332
a=rtcp-mux
a=rtcp-rsize 

Do you have any inputs on how to run the media server in an architecture where the server is hosted on a private IP masked by a public IP? 
Are there any steps to take before we initiate recording in such an infrastructural setup?

**Comment by murillo128** [comment]
You should just use the external ip address as `ip` parameter when creating the endpoint

https://github.com/medooze/media-server-node/blob/master/api.md#createendpoint

**Comment by beingmountain23** [comment]
I am using the external IP address itself, to create the endpoint.
Even then it is not creating the file dump. The tracks are present in the peer connection object.
Everything is as demonstrated in your dummy project.

**Comment by murillo128** [comment]
```
a=candidate:1 1 UDP 2130706431 34.93.161.175 50808 typ host
```
is this the correct ip address? check that with a network capture on both client and server if your browser is actually sending any data to that ip/port and if the firewalls are correctly opened so the server receives it.

**Comment by beingmountain23** [comment]
Hi @murillo128,
Sorry for the delayed response.
I compared the logs of a locally hosted Medooze Server scenario where files were created and recording was dumped successfully, with the failed Google Instance scenario, as explained in the issue description.
I found that the DTLS handshake did not occur, due to which the UDP channels were not established for transmitting streams from my client.
The log screenshot of the Google Instance is shown below:
![Issue DTLS](https://user-images.githubusercontent.com/31466986/64605260-bc09fa80-d391-11e9-9000-290eb2ddf948.png)


As you can see the DTLS handshake logs are not present, from which I can understand that the handshake has not occured.

The file that is created, is always of 444 bytes in size.

Is there any reason for WebRTC  to not perform the DTLS handshake automatically, as expected?

All required tracks are present in the Peer Connection object sent from the Client Side, and the endpoint is the external IP of the server. So necessary medooze server configurations are set as expected.

**Comment by murillo128** [comment]
Can you enable the debug and ultra debug logs on the media server and send the new console log?

Also, can you check on `chrome://webrtc-internals` what are the ice events?

**Comment by beingmountain23** [comment]
Hi @murillo128 
I enabled the debug and ultra-debug as suggested.
This is the log:
![DTLS Not Setup Yet](https://user-images.githubusercontent.com/31466986/65876911-105c3500-e3a8-11e9-8ce4-049471b28b08.PNG)

The WebRTC Internals looks like this:
![WebRTC Internals ICE Candidates](https://user-images.githubusercontent.com/31466986/65876939-20741480-e3a8-11e9-80d3-d27131adbf70.PNG)

Please tell me what I am doing wrong. 
The DTLS establishment is not happening successfully .

**Comment by murillo128** [comment]
The ICE connection has failed, either provided `ip` address is not correct, or udp ports are not open on GCE firewall. 

Take a network capture on client and server to compare traces. You would probably see that no ICE request are being received at server.

**Comment by murillo128** [comment]
please reopen if you still have issues with this
