### ISSUE TITLE
Player component doesn't work

### ISSUE THREAD

**Issue by bakoushin** [medooze/media-server-node#108]
`Player` component doesn't play any of `mp4` files, including the ones recorded via the `Recorder` component.

Repo is provided to simplify reproduction.

### Steps to reproduce:

1. Clone the following repo: https://github.com/bakoushin/medooze-player.git
2. Install dependencies: `npm install`
3. Start server: `npm start`
4. Navigate to http://localhost:3000
5. Make a recording: click `Record` button to start recording. After a while stop recording. File `recoding.mp4` will be created in the script directory.
6. Playback a recording: click `Play` button. Playback unexpectedly won't start.

### Expected behavior: 

Playback will start and play back recorded file.

### Logs

```
[0x7ff013214740][1568970781.226][LOG]>MP4Streamer::Open() [recording.mp4]
[0x7ff013214740][1568970781.226][LOG]-MP4Streamer::Open() | Found hint track [hintId:2]
[0x7ff013214740][1568970781.227][LOG]-MP4Streamer::Open() | Streaming media [trackId:1,type:"vide",name:"VP8",payload:101]
FindTrackId: Track index doesn't exist - track 1 type hint (../external/mp4v2/lib/src/mp4file.cpp,3002)
[0x7ff013214740][1568970781.227][LOG]-MP4Streamer::Open() | Found hint track [hintId:0]
FindTrackIndex: Track id 0 doesn't exist (../external/mp4v2/lib/src/mp4file.cpp,3016)
FindTrackId: Track index doesn't exist - track 0 type text (../external/mp4v2/lib/src/mp4file.cpp,3002)
[0x7ff013214740][1568970781.228][LOG]>MP4Streamer:Play()
[0x7ff013214740][1568970781.234][LOG]<MP4Streamer:Play()
[0x7fefeffff700][1568970781.234][LOG]>MP4Streamer::PlayLoop()
GetSampleTimes: sample id out of range (../external/mp4v2/lib/src/mp4track.cpp,1100)
```

**Comment by pradeep538** [comment]
@murillo128 Any update on this issue, even in [demo](https://github.com/medooze/media-server-demo-node.git) application playback is not working.

Thanks in advance.

**Comment by murillo128** [comment]
should be fixed now. please test.

**Comment by bakoushin** [comment]
Cannot play `VP8` recordings. With `H264` recordings everything is okay.

The `outgoingStream.getStats()` shows all zeros when attached to player playing `VP8` recording.

**Comment by murillo128** [comment]
Have you tried playing them with vlc?

**Comment by bakoushin** [comment]
Sure. The recordings are valid and are playing in VLC correctly.

**Comment by pradeep538** [comment]
Even I have tested recordings are playing in VLC.

**Comment by murillo128** [comment]
VP8 inside mp4 is not supported by all players as it is a recent standard, it will play fine on vlc and chrome, but not on Qt or ipad/ios

**Comment by bakoushin** [comment]
The issue is that vp8 mp4 recorded via Recorder component is not played by the Player component.

**Comment by murillo128** [comment]
could you send me a sample of a failing vp8 recording for testing locally? are you generating them with chrome or firefox?

**Comment by bakoushin** [comment]
I'm generating them from Chrome and from Firefox as well.

Samples:

1. VP8 from Chrome: https://github.com/bakoushin/medooze-player/blob/recording/recording_vp8_chrome.mp4
2. VP8 from Firefox: https://github.com/bakoushin/medooze-player/blob/recording/recording_vp8_firefox.mp4
3. H264 from Safari: https://github.com/bakoushin/medooze-player/blob/recording/recording_h264_safari.mp4

I've created a quick demo, which just creates a file using `Recorder`, then plays it back using `Player`:  https://github.com/bakoushin/medooze-player/
