### ISSUE TITLE
Provide ICE servers and relay candidates in answer to client

### ISSUE THREAD

**Issue by AgentForty7** [medooze/media-server-node#110]
Hi @murillo128 
I am trying to use a TURN server to relay my media streams because my client code is behind a proxy.
I have specified relay candidates in the offer sent to the Medooze Server.

Unfortunately, the only candidate pair created successfully, is a relay and local pair. Relay candidate from client side and local condidate from the medooze server.
As shown below, a screeshot from WebRTC internals:
![webrtc internal ss](https://user-images.githubusercontent.com/51798375/65662783-c34c2c00-e052-11e9-90e1-16a35d7cde91.png)

Here the remoteAddress seen is the Medooze Server Endpoint, this is a candidate of type: local and the local address is the TURN relay address from my proxy blocked client system.
This is the only candidate pair created which is not able to relay any data.

I want to implement a relay-relay candidate pair(which I am sure will work for a proxy situation) for which I need to specify ICE servers on the Medooze server side code too.

Is this scenario possible? Are there any api's exposed for me to specify ICE servers? 

Is there any flaw with my approach? Because as far as I have observed in my previous WebRTC implementations, whenever a relay-local candidate pair is implemented, it never completes the ICE establishment but a relay-relay ICE candidate always works.

**Comment by dt-atkinson** [comment]
I don't think I fully understand what you are trying to do.

However, I have seen that when you call `createTransport` on the `Endpoint` you can supply local and remote info. This is an `SDPInfo` object which you can add ICE candidates to.

https://medooze.github.io/media-server-node/#endpoint
https://medooze.github.io/semantic-sdp-js/#sdpinfo

**Comment by murillo128** [comment]
The media server as as ICE lite with only a single ice udp candidate on its side.  It is meant to be run on behind a public IP with no NAT/FW issues.

On that regards, it is not possible to configure any STUN server on the media server side.

Anyway, what you are referring is to configure a TURN server on the client side and use the relay candidate from it. This has nothing to do with the media server as the media server will just be passive and accept ICE binding request from any remote ice candidate (either host, relay or reflx).  So I will mark this issue as invalid and close it. 

Anyway, if you want to test relay candidates on client, just block udp ports and configure a turn server with tcp/tls.
