### ISSUE TITLE
error: in method 'PropertiesFacade_SetPropertyStr'

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#115]
I have seen this a couple of times when I believe my application is trying to create transports:
```
error: in method 'PropertiesFacade_SetPropertyStr', argument 3 of type 'char const *'
```
I have not found a way to reproduce it yet

**Comment by murillo128** [comment]
SWIG wrappers is quite strict with the kind of types it requires, take care about json parsing returning Number instead of String or similar. I could add explicit conversion to prevent this on js.

**Comment by dt-atkinson** [comment]
I have had a look - do you think this could be from an SDP I pass in?

**Comment by murillo128** [comment]
yes, maybe some values like "1" are converted to numbers or something similar, if you get which property is causing the issue it will be easier to solve.

**Comment by dt-atkinson** [comment]
I'll add in some extra debug, cheers

**Comment by dt-atkinson** [comment]
Could be when `ice-ufrag:` in SDP is generated as a number client-side?

Have a few matching SDPs like this

**Comment by murillo128** [comment]
added an explicit `String` conversion, should not happen again.

**Comment by dt-atkinson** [comment]
Tested and all looking good!
