### ISSUE TITLE
Can't record video

### ISSUE THREAD

**Issue by otkelbay** [medooze/media-server-node#118]
Hello, i am trying to record video.
1)My steps installed my application to ubuntu 16 server.
2)Installed medooze-media-server to same server with the same public ip.
3)Opened all ports to udp and tcp.
4)Developed signaling process

So i am my sdp offer:
v=0
o=- 5109389436380781354 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:E02A
a=ice-pwd:vPwzr+NI1MWLU3izm2ZNHrPq
a=ice-options:trickle
a=fingerprint:sha-256 33:68:59:6C:61:07:AD:67:0C:76:35:5B:3C:91:4E:5C:FB:EC:A7:98:77:99:3B:F8:20:30:65:14:57:39:E0:46
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4 bf36f6ba-b219-4bf7-be0e-a8034851b5da
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2507794630 cname:zufa5fDrr+ipjzJ5
a=ssrc:2507794630 msid:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4 bf36f6ba-b219-4bf7-be0e-a8034851b5da
a=ssrc:2507794630 mslabel:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4
a=ssrc:2507794630 label:bf36f6ba-b219-4bf7-be0e-a8034851b5da
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:E02A
a=ice-pwd:vPwzr+NI1MWLU3izm2ZNHrPq
a=ice-options:trickle
a=fingerprint:sha-256 33:68:59:6C:61:07:AD:67:0C:76:35:5B:3C:91:4E:5C:FB:EC:A7:98:77:99:3B:F8:20:30:65:14:57:39:E0:46
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:12 urn:3gpp:video-orientation
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4 0e150a78-1007-407d-8a94-318fafe7a39c
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 red/90000
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:123 ulpfec/90000
a=ssrc-group:FID 1528790413 2665166988
a=ssrc:1528790413 cname:zufa5fDrr+ipjzJ5
a=ssrc:1528790413 msid:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4 0e150a78-1007-407d-8a94-318fafe7a39c
a=ssrc:1528790413 mslabel:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4
a=ssrc:1528790413 label:0e150a78-1007-407d-8a94-318fafe7a39c
a=ssrc:2665166988 cname:zufa5fDrr+ipjzJ5
a=ssrc:2665166988 msid:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4 0e150a78-1007-407d-8a94-318fafe7a39c
a=ssrc:2665166988 mslabel:G3GK2nErOzlHYtw4db7ZD9gfaNX7qqmn1MY4
a=ssrc:2665166988 label:0e150a78-1007-407d-8a94-318fafe7a39c

Sdp answer from medooze-media-server:
v=0
o=- 1570029082820 1 IN IP4 127.0.0.1
s=semantic-sdp
c=IN IP4 0.0.0.0
t=0 0
a=ice-lite
a=msid-semantic: WMS *
a=group:BUNDLE 0 1
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap-allow-mixed
a=setup:passive
a=mid:0
a=sendrecv
a=ice-ufrag:5ddd32fd255815a4
a=ice-pwd:07b5cf44e08b4f7ccc5a8648d2ccaaf7e27083c32616d1c0
a=fingerprint:sha-256 B1:4B:21:2A:6B:49:F8:75:1B:06:3C:3B:A9:BD:4F:F4:79:91:86:33:4D:28:72:BD:07:CB:87:A7:4F:6E:89:7F
a=candidate:1 1 UDP 2130706431 167.71.74.63 48058 typ host
a=ssrc:23318782 cname:d2ee780d-cd7a-49f9-837c-20471a290372
a=ssrc:23318782 msid:d2ee780d-cd7a-49f9-837c-20471a290372 audio2
a=rtcp-mux
a=rtcp-rsize
m=video 9 UDP/TLS/RTP/SAVPF 98 99 100 101 102 122 125 107
a=rtpmap:98 VP9/90000
a=rtpmap:99 rtx/90000
a=rtpmap:100 VP9/90000
a=rtpmap:101 rtx/90000
a=rtpmap:102 H264/90000
a=rtpmap:122 rtx/90000
a=rtpmap:125 H264/90000
a=rtpmap:107 rtx/90000
a=fmtp:99 apt=98
a=fmtp:98 profile-id=0
a=fmtp:101 apt=100
a=fmtp:100 profile-id=2
a=fmtp:122 apt=102
a=fmtp:102 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
a=fmtp:107 apt=125
a=fmtp:125 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
a=rtcp-fb:98 transport-cc 
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack 
a=rtcp-fb:98 nack pli
a=rtcp-fb:100 transport-cc 
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack 
a=rtcp-fb:100 nack pli
a=rtcp-fb:102 transport-cc 
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli
a=rtcp-fb:125 transport-cc 
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli
a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap-allow-mixed
a=setup:passive
a=mid:1
a=sendrecv
a=ice-ufrag:5ddd32fd255815a4
a=ice-pwd:07b5cf44e08b4f7ccc5a8648d2ccaaf7e27083c32616d1c0
a=fingerprint:sha-256 B1:4B:21:2A:6B:49:F8:75:1B:06:3C:3B:A9:BD:4F:F4:79:91:86:33:4D:28:72:BD:07:CB:87:A7:4F:6E:89:7F
a=candidate:1 1 UDP 2130706431 167.71.74.63 48058 typ host
a=ssrc:175986446 cname:d2ee780d-cd7a-49f9-837c-20471a290372
a=ssrc:175986446 msid:d2ee780d-cd7a-49f9-837c-20471a290372 video3
a=ssrc:1503129467 cname:d2ee780d-cd7a-49f9-837c-20471a290372
a=ssrc:1503129467 msid:d2ee780d-cd7a-49f9-837c-20471a290372 video3
a=ssrc:354981026 cname:d2ee780d-cd7a-49f9-837c-20471a290372
a=ssrc:354981026 msid:d2ee780d-cd7a-49f9-837c-20471a290372 video3
a=ssrc-group:FID 175986446 1503129467
a=ssrc-group:FEC-FR 175986446 354981026
a=rtcp-mux
a=rtcp-rsize

**Connecting and joining is ok, but video doesn't record**
Error is: [DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet

My logs:

![image](https://user-images.githubusercontent.com/43276802/66056148-80a9b880-e558-11e9-98bc-e14db44b4606.png)

![image](https://user-images.githubusercontent.com/43276802/66056209-95864c00-e558-11e9-955e-a7c5fafc8f4f.png)
![image](https://user-images.githubusercontent.com/43276802/66056222-a040e100-e558-11e9-9232-e6dc17e5595c.png)
![image](https://user-images.githubusercontent.com/43276802/66056275-b3ec4780-e558-11e9-9763-24d7bebce6ec.png)
![image](https://user-images.githubusercontent.com/43276802/66056314-bf3f7300-e558-11e9-819b-e818d1f2396f.png)

**Comment by murillo128** [comment]
There server is not receiving any ICE binding request from browser, so DTLS cannot start. Please, take a network capture on browser and server and ensure to verify it and check that the firewalls are opened correctly.

**Comment by otkelbay** [comment]
I had to disable firewall by sudo ufw disable, thank you very much!
