### ISSUE TITLE
broadcast to rtmp

### ISSUE THREAD

**Issue by quickstreamingmedia** [medooze/media-server-node#12]
how to broadcast to rtmp from nodejs

**Comment by murillo128** [comment]
It is not possible yet, not sure if I would expose it, do you think it is usefull (given that audio is OPUS)?

**Comment by quickstreamingmedia** [comment]
can trans code in server side iff need hls output

**Comment by notedit** [comment]
+1 for this,  we now use ffmpeg do this

**Comment by murillo128** [comment]
I am considering adding rtmp support as an independent package `medoose-media-server-rtmp`, after all most of the code is already in place https://github.com/medooze/media-server/tree/master/src/rtmp

Just to confirm, would be plain rtmp just work for you? that is, no ssl and no rtmpfp.

Also, most probably also add another packate `medooze-media-server-codecs` to support h264 and vp8 encoding/decoding, opus decoding/encoding and aac encoding.

Would that be enough for you? Also, do you have any public rtmp serve which I could use for testing and validating implementation?

**Comment by notedit** [comment]
plain rtmp is ok.  i am using  https://github.com/illuspas/Node-Media-Server  for testing

**Comment by murillo128** [comment]
Could you create a repo with a simple app which I could use for testing?
```
browser =(webrtc)=> medooze =(rtmp)=> your app =(hls)=> browser
```

**Comment by notedit** [comment]
now  we do not use medooze to do this yet,  we use mediasoup before and forward the  audio/video rtp data to ffmpeg then we do recorder and  transcode to rtmp  use my  little lib  https://github.com/notedit/rtprecorder.

but mediasoup v2's  is a little hard for iOS/Android/Windows native code to use,  it does not use SessionDescription.  so i am investigating medooze,  medooze looks great.

**Comment by murillo128** [comment]
@notedit  how do you send the data to rtprecorder? If you send it over rtp/udp you can do the same with  https://medooze.github.io/media-server-node/#streamer

**Comment by notedit** [comment]
yes,  we send it over rtp/udp,  i will have a look at  streamer. thanks

**Comment by notedit** [comment]
in fact, if we send media over rtp/udp to external ffmpeg process, the delay will  be  several  seconds, that is not so good.

**Comment by notedit** [comment]
@murillo128   hi,  will this feature will going on?   it is useful to communicate with old rtmp system.

**Comment by murillo128** [comment]
I will try to create a module to support rtmp, would pcmu/a work for no? If not I will have to create also an audio codec module

**Comment by notedit** [comment]
i think rtmp use h264/aac,  we do not need to do video transcode,  just audio trancode works fun.

**Comment by notedit** [comment]
i see all the code in  rtmpmp4stream,  what we need to do some audio codec transcode.

**Comment by notedit** [comment]
We can broadcast to rtmp now,  see the demo https://github.com/notedit/media-server-go-demo/tree/master/webrtc-to-rtmp

**Comment by quickstreamingmedia** [comment]
so whats updated it ?

**Comment by notedit** [comment]
https://github.com/notedit/media-server-go-demo/blob/master/webrtc-to-rtmp/server.go#L113

you can get the mediaframe and then handle it use gstreamer/ffmpeg.

**Comment by tkmn0** [comment]
Hi, 
Could you let me know how to concat rpt video streams like MCU with ffmpeg,
or, how to handle raw video data with node.js?

My goal is as below.
`medooze =(rtp streams)=> ffmpeg (make streams one stream like MCU) =(rtmp)=> my app =(hls)=> browser `
I sent rtp stream with streamer (https://medooze.github.io/media-server-node/#streamer).
Then, I used ffmpeg to receive rtp stream from medooze.
Actually, I succeeded to create mp4 file from a video rtp stream & an audio rtp stream.

However,
Then when I tried to  concat two video rtp streams like MCU server using ffmpeg, 
ffmpeg showed the message `non-existing PPS 0 referenced`.

SDP for ffmpeg to receive rtp stream was as below.
`
v=0
o=- 0 0 IN IP4 127.0.0.1
s=semantic-sdp
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 56.40.101
m=video 5014 RTP 96
a=rtpmap:96 H264/90000
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
`

Best regards.

**Comment by notedit** [comment]
@tkmn0 media-server support media mixer.  but media-server-node does not support it.  
Media mixer cost  lots of cpu.  Maybe i will add some media mixer feature based on gstreamer,  but that based on my free time.

**Comment by tkmn0** [comment]
@notedit 
Thanks for your advice.
I see that media mixer needs a lot of cpu. 
Anyway, I will try to use gstreamer!
Thasnks

**Comment by murillo128** [comment]
Initial alpha rtmp support available here: https://github.com/medooze/rtmp-server-node

Only rtmp-in supporte currently (and no audio transcoding yet), but please feel free to try it.

**Comment by murillo128** [comment]
Issue cloned there https://github.com/medooze/rtmp-server-node/issues/1
