### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by eolme** [medooze/media-server-node#120]
I read the previous issues about Windows support. What's missing for it to work on Windows? Do you want some help implementating that?

**Comment by murillo128** [comment]
Would be tricky, would require to change all mutex/threads from pthreads to c++ std ones (doable but requires a lot of changes), support windows socket stuff and then then check what other stuff needs to be changed.

Not on my priorities, so unlikely to happen. I know it is not what you have asked for, but would you consider using the linux susbsystem for windows? should work

**Comment by Tymek** [comment]
It should be possible to run it in docker, right? I'm not able to start `master` neither on linux (arch, node 13) nor in docker (node 10 or 12) at the moment. Similar results. [Output in gist](https://gist.github.com/Tymek/690302632d90b412f6859a627614d2bc)

**Comment by murillo128** [comment]
If you could write a small readme about how to get it running on docker it would be very helpful

**Comment by Tymek** [comment]
2 important undocumented things where
- proper versions (I got it working with node 10 and gcc 8 I think - image `node:10-buster`)
- `git submodule update --init --recursive`

After that is solved, (and fyi, you need to enable shared drives in docker settings), in PowerShell, in project root directory:
```
docker run --rm -it -w="/srv" -v ${PWD}:/srv node:10-buster bash -c "npm i && npm run-script dist"
```
(after some compiling) library is ready in `dist` and can be used in other project that runs in docker.

I still don't know how to deal with 'random' ports. `network_mode: host` didn't work, but that might be just my machine.

**Comment by murillo128** [comment]
>BTW, will I be able to do it without parts under GPL license?

The project is MIT so you should not have any issue with the license (the GPL parts of the c++ media server are not included here).

**Comment by agouaillard-cosmo** [comment]
@agouaillard-cosmo write corresponding documentation.
