### ISSUE TITLE
Is there any example of Rtp-in ?

### ISSUE THREAD

**Issue by tkmn0** [medooze/media-server-node#130]
Hi, Thanks for your project.
Is there any example of Rtp-in? 
I tried Rtp-out with StreamerSession, then, I could receive rtp stream using gstreamer.
However, I could not receive rtp stream from gstreamer with StreamerSession.
I think some example for rtp in/out with gstreamer/ffmpeg  could be helpful for us. 
Best regards.

**Comment by notedit** [comment]
https://github.com/notedit/rtmp-to-webrtc

**Comment by tkmn0** [comment]
@notedit 
Thanks! I will check your repository !! :)

**Comment by tkmn0** [comment]
@notedit 
Thanks for your project! 
I could receive rtp stream from gstreamer and send it back to browser!! :)
