### ISSUE TITLE
Media Recording 

### ISSUE THREAD

**Issue by michaelfemi81** [medooze/media-server-node#132]
The mp4 file recorded is not usable. Even playback and simulcast examples are not working

**Comment by michaelfemi81** [comment]
Error: MP4 filenamec could not be opened when playback tried to play generated file

**Comment by murillo128** [comment]
What player are you using for playback? Can you provide a sample recroded file?

**Comment by michaelfemi81** [comment]
I used Vlc and quicktime player. 
https://www.dropbox.com/s/yp19s6bliry99qj/1580466919522.mp4?dl=0

**Comment by murillo128** [comment]
are you calling the `recorder.stop()` and waiting for it to finalice? Can you enable debug logs and send the output of the console to me?

**Comment by michaelfemi81** [comment]
Its playable on VLC when I call recorder.stop() thanks alot

**Comment by michaelfemi81** [comment]
I still get this error on playback "MP4 filenamec could not be opened"

**Comment by murillo128** [comment]
due to codecs support, it may only be playable on VLC or new players. QuickTime player won't support VP8, VP9 or OPUS.
