### ISSUE TITLE
Unable to create media server binary bundle 

### ISSUE THREAD

**Issue by pradeep538** [medooze/media-server-node#137]
hi @murillo128 ,

Thanks for your effort on the media server and made it opensource.

Am facing an issue while creating creating binary tar as specified in github repo.
When i run this command "npm run-script dist" am getting below error 
but am able to sucessfully run media-server-demo-node app.

make: Entering directory '/root/media-server-node/build'
make: *** No rule to make target 'Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem_posix.o', needed by 'Release/obj.target/external/mp4v2/libmp4v2.a'.  Stop.
make: Leaving directory '/root/media-server-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/root/.nvm/versions/node/v10.19.0/bin/node" "/root/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--jobs=max"
gyp ERR! cwd /root/media-server-node
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.87.0 dist: `node-gyp configure && node-gyp build --jobs=max && mkdir -p dist && tar cvzf dist/medooze-media-server-`node -e 'console.log(require("./package.json").version)'`.tgz `([ "$(uname)" = 'Darwin' ] && echo "-s |^|medooze-media-server/|") || echo " --transform=flags=r;s|^|medooze-media-server/|"` package.json index.js medooze-media-server.d.ts README.md lib/* build/Release/medooze-media-server.node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.87.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-05T12_53_46_620Z-debug.log

Thanks in advance,
Could you please help.

**Comment by kelexel** [comment]
Hello, I'm jumping in, since I face the same issue..
Tested using OSX  10.15.4, node v12.16.1 and node v10.19.0.
Build fails at same point

**Comment by murillo128** [comment]
you have not initiated the git submodules, try:

git submodule update --init --recursive

**Comment by kelexel** [comment]
Indeed, this solves this issue !
And shame on me for not reading the manual :)

I now have an ELIFECYCLE error while compiling, and I'm investigating why...
But, I think this current issue can be considered is resolved ?

**Comment by pradeep538** [comment]
Hi @murillo128 ,
Thanks for your help, as you said it worked to bundle the binary but when am using it with node application i did install by the command 
"npm i --save medooze-media-server-0.87.0.tgz" 
but while starting node application
 -> node index.js <Public ip>
 it is giving me error saying 

Illegal instruction (core dumped)

Thanks in advance.

**Comment by murillo128** [comment]
could you generate a core dump file and get a back trace of it with `gdb`?

```
gdb node core
> bt
```

**Comment by pradeep538** [comment]
@murillo128 
I have generated another bundle it worked seamlessly.
I would like to Thank You once again for your awesome work towards this project,
Only highly skilled people on media technologies could be able to make an application like WebRTC SFU's but your project made possible for a web developer to build an application on media.
I would like to appreciate your concept of making raw nodejs API without relying on signaling embedded library.

**Comment by murillo128** [comment]
thank you for your kind words! closing the issue now.
