### ISSUE TITLE
Recorder outputs empty 444 bytes mp4 files

### ISSUE THREAD

**Issue by fughur** [medooze/media-server-node#138]
Hello! 
I'm getting unplayable 444 byte mp4 files from recorder while using both the [demo](https://github.com/medooze/media-server-demo-node) or my team old setup (was working in october-december 2019).

**Environment**
- Window 10 (wsl / docker)
- Node 10.19
- Latest chrome (80.0.3987.149) / Firefox 74.0 for client

**What i'm tried**
- WSL and `ubuntu:bionic`-based docker 
- Different media-server versions (from 0.81 to 0.87)

**Steps to reproduce (wsl / ubuntu)**
1) Clone https://github.com/medooze/media-server-demo-node
2) Install dependencies (`npm i && npm i medooze-media-server`)
3) Run `node index.js 127.0.0.1`
4) Navigate to `https://127.0.0.1:8000/rec/` and then close tab after a few minutes of recording
5) Observe 444 byte mp4 inside `./recordings` 

**Steps to reproduce (docker)**
1) Clone https://github.com/medooze/media-server-demo-node
2) Create Dockerfile (see below) and build it using 
`docker build -t medooze-demo:test -f Dockerfile .`
3) Run it
 `docker run -p 8000:8000 -p 3350:3350 --name medooze-demo -d medooze-demo:test forever index.js 127.0.0.1 &`
4) Navigate to `https://127.0.0.1:8000/rec/` and then close tab after a few minutes of recording
5) Observe 444 byte mp4 inside `./recordings` (to copy it from docker run
`docker cp medooze-demo:/usr/media-service/recordings ./recordings_from_docker`
and then navigate to `./recordings_from_docker`)

**My dockerfile** 
```
# Base ubuntu
FROM ubuntu:bionic

# Install dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
    apt-transport-https \
    ca-certificates \
    software-properties-common \
    lsb-core \
    libgsm1-dev \
    libtool \
    subversion \
    git \
    libgcrypt11-dev \
    libssl-dev \
    bzip2 \
    pkg-config \
    libgtk2.0-dev \
    libnss3-dev \
    libxtst-dev \
    libxss-dev \
    libdbus-1-dev \
    libdrm-dev \
    libgconf2-dev \
    libgnome-keyring-dev \
    libpci-dev \
    libudev-dev \
    ffmpeg \
    gpg-agent \
    less \
    curl \
    wget \
    g++ \
    make \
    automake \
    autoconf \
    mp4v2-utils \
    git \
    ssh

# Install NodeJS 10.x directly
WORKDIR /usr/media-service
RUN curl https://deb.nodesource.com/setup_10.x -sL --output setup-nodejs.sh
RUN /bin/bash setup-nodejs.sh
RUN apt-get install -y nodejs
RUN rm setup-nodejs.sh

# Copy all required modules
COPY ./ ./

# Expose ports
EXPOSE 3350 8000

# Install dependencies
RUN npm i
RUN npm i forever -g

# Specify any version here
RUN npm i medooze-media-server

# Startup our server
RUN forever index.js 127.0.0.1 &
```
**Additional**

I also found similar bug inside demo repository with other environment cases https://github.com/medooze/media-server-demo-node/issues/23.
Creating the new issue here as i think it isn't related to demo code (my team's setup was working well in october-december).

**Comment by bukaspace** [comment]
Hi everyone, 
I can confirm the same behavior compiling on Ubuntu and Alpine linux.
Meantime it build and work fine on Mac:
 - x86_64-apple-darwin19.4.0
 - clang-1103.0.32.29
 - Node 10.19.0
 - npm 6.13.4

**Comment by McMainsLiam** [comment]
I'm also getting the same issue on my Mac. Would love to see some update on this either in this repo or [the demo repo](https://github.com/medooze/media-server-demo-node/issues/23)! 

• node v10.10.0 
• npm v6.4.1
• MacOS Catalina 10.15.2

**Comment by bukaspace** [comment]
@McMainsLiam could you please also specify your C compiler? (Usually, the output of gcc —version).
I’m asking, because there are some C code underneath the hood.

**Comment by McMainsLiam** [comment]
Sure! Let me know if there is anything else!

```
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
```

**Comment by murillo128** [comment]
Could you check with latest version please? Lot's of fixes in mp4 recordings.

**Comment by fughur** [comment]
@murillo128 tried to run demo with latest version (0.88.0) using both WSL and bionic docker - it still only produces 444 byte recordings.

**Comment by murillo128** [comment]
Is the ICE connection being established at all? check in chrome://webrtc-internals if there is any data being sent at all to the server. Also double check if you are setting the external server IP when running the demo.

Last thing, you can use the `Transport.dump()` to dump the incoming traffic and double check it is being received by the server.

**Comment by andpap** [comment]
thanks, the problem was resolved;

everything is working on win10 with docker, just need use external server IP and publish udp necessary ports in docker

**Comment by fughur** [comment]
I can confirm that everything is working now after publishing udp ports, binding server to actual external service ip and updating to latest medooze (0.95.0)
