### ISSUE TITLE
problem with installing media-server-node

### ISSUE THREAD

**Issue by hanios123** [medooze/media-server-node#141]
i  have decided to try out medooza  media server, and I got some problem while installing it,
I have excuted the command npm i --save medooze-media-server,  I have node  v12.16.2,node-gyp v5.1.0, any help will be appreciated.

I got this problem 
49 warnings generated.
3 warnings generated.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /Users/user/Documents/oviceWorkspace/mediaServer/media-server-client-js/demo/node_modules/medooze-media-server
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.88.0 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.88.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-04-20T13_31_36_797Z-debug.log

**Comment by murillo128** [comment]
see #80
