### ISSUE TITLE
Video mixing with continuous presence

### ISSUE THREAD

**Issue by PNixx** [medooze/media-server-node#143]
When is support planned?

**Comment by murillo128** [comment]
Although there is code on the c++ side, I don't expect to implement  the mixing with continuous on the node side. At least until there is a customer request that requires it.

**Comment by PNixx** [comment]
@murillo128 What customer request are you talking about?

**Comment by agouaillard-cosmo** [comment]
Please do not comment on closed tickets. I'm going to answer this time, by courtesy, but please don't.
The sentence is clear: unless someone is ready to pay for this, "until there is a customer request", it will not happen. If you want to sponsor this effort, please let us know at contact@cosmosoftware.io and someone will send you a quote.
