### ISSUE TITLE
Outgoing Stream Tracks - Apply Resolution Constraints Dynamically

### ISSUE THREAD

**Issue by triethyl** [medooze/media-server-node#148]
Can we somehow dynamically change the bitrate of an [OutgoingStreamTrack](https://medooze.github.io/media-server-node/#outgoingstreamtrack) object?

It will be especially beneficial when supporting streams with changing network conditions and in cases wherein the client has control over the resolution of the feeds that he receives.

For those who are familiar with Web's MediaStreamTrack object, I wish of something like [applyConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/applyConstraints).

**Comment by murillo128** [comment]
There was an issue with the jsdoc and the `setTargetBitrate()'  method was missing:

https://github.com/medooze/media-server-node/blob/master/lib/Transponder.js#L166

You can set the target bitrate on the transponder when you attach an outgoingtrack to an incoming track.

Note that the sfu can only control the outgoing bitrate by switching between simulcast or SVC layers. You will have to do this periodically so the best one is choosen accordingly (tipically you will like to listen to the transport bitrate event for that).

**Comment by triethyl** [comment]
From what I understand, `setTargetBitrate()` method can be called and set only once, before attaching to the Incoming Stream. That doesn't take into account dynamically switching to a bitrate.

How can we switch between simulcast or SVC?

Also, whose target bitrate does the `targetbitrate` event present in the transport layer inform us about - the sfu side one or the client's?
