### ISSUE TITLE
OpenSSL handshake never completes on remote domain

### ISSUE THREAD

**Issue by benbatya** [medooze/media-server-node#150]
This is related to [#46 ](https://github.com/medooze/media-server-node/issues/46)

I believe that the problem is that that SSL_CTX_set_info_callback() is never called with where==SSL_CB_HANDSHAKE_DONE so DTLSConnection::SetupSRTP() is never called.
This shows up in the log (line 33) where the  "DTLS handshake starts" but "DTLS handshake done" is never displayed.

I'll add more info as I find it

[media-server-openssl-error.log](https://github.com/medooze/media-server-node/files/4598406/media-server-openssl-error.log)

**Comment by bensch128** [comment]
Oh, this happens with the media-server-demo-node in the /svc demo.
Thanks!

**Comment by bensch128** [comment]
I pulled out the handy wireshark and it seems like the handshake never completes because the server doesn't receives the ClientKeyExchange message or the server never sends the ChangeCipherSpec message as per [this article](https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/)

Any ideas?
More investigation is needed...

![wireshark](https://user-images.githubusercontent.com/63752/81447343-53963780-9131-11ea-8731-617890815e59.png)

**Comment by murillo128** [comment]
that seems the ws connection not the DTLS one (note the port 8000). First check that your ws is conencting correctly (accept the self signed SSL certificates) and then check the ip address you are using on the server is the publich ip address

**Comment by bensch128** [comment]
I filtered out the ports to just 8000.
It seems like there is eventually a New Session Ticket at packet 79 but the SSL_CB_HANDSHAKE_DONE is never received. I wonder if the multiple "Client Hello"s is playing havok with the openssl state machine??

![Screenshot_20200508_145507_blurred](https://user-images.githubusercontent.com/63752/81452676-564a5a00-913c-11ea-874c-92e027281d00.png)

**Comment by bensch128** [comment]
The server IP has the correct ipv4 address. interestingly the ssh uses the ipv6 address...

**Comment by murillo128** [comment]
DTLS is udp, you are checking the TLS connection for the websocket connection.

**Comment by bensch128** [comment]
So what should I be filtering for? there's no udp communication over port 8000

**Comment by murillo128** [comment]
check on the browser javascript console that the websocket connection is successfully connected, if not, nothing will work.

**Comment by bensch128** [comment]
console looks good... :-)

[ww-client-output.txt](https://github.com/medooze/media-server-node/files/4602229/ww-client-output.txt)

I checked that I could connect to the wss and after switched server certs, 
I finally figured out that the bundled one was required.
