### ISSUE TITLE
Audio mixing in 8khz,16Khz,32khz and 48Khz in node

### ISSUE THREAD

**Issue by pradeep538** [medooze/media-server-node#151]
Hi @murillo128 ,
Sorry for creating the issue for just information's sake. Please let us know if you have any communication channel like slack or something.

Just i wanted to know the audio mixing 8khz(16 bit)  is available in node or not.
I wanted to achieve two things below
1. In multi-party conference if i want to attach every other party's audio to one so in this scenario we need to mix all-party audio and attach to one or how it works in media-server-node.
2. How to encode 8khz (16 bit) audio to integrate with any speech recognition system .

Thanks,
Pradeep M R.

**Comment by murillo128** [comment]
Audio mixing is not yet supported. However, preliminary support for audio encoding/decoding can be found here:

https://github.com/medooze/audio-codecs-node

https://groups.google.com/forum/#!forum/medooze

**Comment by murillo128** [comment]
for further questions, please ask in 

https://groups.google.com/forum/#!forum/medooze
