### ISSUE TITLE
Cant compile on osx 10.15.4

### ISSUE THREAD

**Issue by Ben-Mark** [medooze/media-server-node#158]
OS: OSX Catalina 10.15.4
Node version: 14.3.0
media-server-node version: 0.94.8
node-gyp version: 7.0.0

npm i error log:
[log](https://pastebin.com/QyfT1HyX)

Note:   git submodule update --init --recursive  didn't work

Thanks in advance.

**Comment by asherkin** [comment]
Only Node v8 and v10 is supported - SWIG hasn't been updated for v12+ yet.
