### ISSUE TITLE
Fatal error installing on OSX ( 10.13.2 (17C88) )

### ISSUE THREAD

**Issue by igrooves** [medooze/media-server-node#16]
Hi there.

I noticed you're now supporting OSX, but i'm having issues building it.

`../media-server/include/xmlrpcserver.h:6:10: fatal error: 'xmlrpc.h' file not found
#include <xmlrpc.h>
         ^~~~~~~~~~
1 error generated.`

**Comment by murillo128** [comment]
Umm.. that file should not be included, could you print the full trace to check where it has been included?

**Comment by igrooves** [comment]
https://github.com/medooze/media-server/blob/04a5d423abb6e662f110a71bb96f1b963d92b70b/include/xmlrpcserver.h#L6

**Comment by igrooves** [comment]
Oh you beat me! 

Magic thanks

**Comment by murillo128** [comment]
Please try new version, this should be fixed. Thanxs for the report!

**Comment by igrooves** [comment]
Yep that sorted it. Thank you!
