### ISSUE TITLE
Error while switching between video/audio only

### ISSUE THREAD

**Issue by hemdan-dev** [medooze/media-server-node#161]
Am using sfu code & added a button for all users to switch camera on or off
And this is my steps to add video in server side
1-get user incoming stream & create video track to this stream & return new incoming stream data
2-update current user outgoing stream in every participant in room to create video in their outgoing streams
Thats works successfully & see video in all participants screens ... but when 2 participants open camera at same time
i see this message and don't know what i can do &  some times this message appear randomly

[0x7f8f267fc700][1594693421.582][ERR]-Got feedback message for unknown media  [ssrc:2362185640]

am just tried to wait updated sdp from client to server but this message still appears

**Comment by murillo128** [comment]
Seems an error on how the api is used. I would need a code snippet about how you are implementing it or a (even better) a github repo in which I can reproduce the issue

**Comment by hemdan-dev** [comment]
https://github.com/hemdan-dev/SFU-Issue

this is a sfu code with some modifications ... am just added two new websocket transactions (startVideo - stopVideo)
try to open two users and mute video & unmute video many times .. i think 14 time this message will appear

thanks ^^

**Comment by dahabit** [comment]
@murillo128 It will be great if we can find a solution for this error

**Comment by murillo128** [comment]
won't be able to take a look at it in next two weeks sorry (i have some deadlines I have to meet)

**Comment by dahabit** [comment]
@murillo128 Thank you
waiting for your update, wish you all the best

**Comment by hemdan-dev** [comment]
Thank you dude ,waiting you ^^

**Comment by kortobaa** [comment]
@murillo128 i know you are so busy but... :( any update for this issue??

**Comment by hemdan-dev** [comment]
@murillo128 i know you are so busy dude but... :( any updates??

**Comment by murillo128** [comment]
One question, is just the trace the issue? or is there any other visible effect?

The trace can happen if the rtp arrives earlier than the sdp is processed, so the ssrc is not yet known and the packets are dropped. It is a harmless error.

**Comment by hemdan-dev** [comment]
No, it has a visible effect, like I mentioned before in my example
https://github.com/hemdan-dev/SFU-Issue
When I try to open two clients and turn off video then turn on repeatedly the error occurs, and after that first participant gets disconnected from session.

**Comment by murillo128** [comment]
How does the participant disconnect? could you enable the debug/ultradebug logs and send me the log portion when the user disconnects?

**Comment by hemdan-dev** [comment]
@murillo128 Thank you so much it's fixed after medooze update ... am just tested it too hard ... the first problem were, when i open camera and close it rapidly sometimes stream info arrive with no data, but this problem just fixed after medooze update ... the second issue when i disconnect from session, there's was a problem with my code and just fixed it.
