### ISSUE TITLE
Buffer.h miss

### ISSUE THREAD

**Issue by SkyShiYan** [medooze/media-server-node#162]
ubuntu 18.04

sudo npm run-script dist. and i have these errors:
which lib should been installed?

In file included from ../src/media-server_wrap.cxx:1618:0:
../src/../media-server/include/media.h:9:10: fatal error: Buffer.h: No such file or directory
 #include "Buffer.h"
          ^~~~~~~~~~
compilation terminated.
medooze-media-server.target.mk:256: recipe for target 'Release/obj.target/medooze-media-server/src/media-server_wrap.o' failed
make: *** [Release/obj.target/medooze-media-server/src/media-server_wrap.o] Error 1
make: Leaving directory '/home/vagrant/media-nodejs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-111-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--jobs=max"
gyp ERR! cwd /home/vagrant/media-nodejs
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! media-nodejs@0.96.1 dist: `node-gyp configure && node-gyp build --jobs=max && mkdir -p dist && tar cvzf dist/medooze-media-server-`node -e 'console.log(require("./package.json").version)'`.tgz `([ "$(uname)" = 'Darwin' ] && echo "-s |^|medooze-media-server/|") || echo " --transform=flags=r;s|^|medooze-media-server/|"` package.json index.js medooze-media-server.d.ts README.md lib/* build/Release/medooze-media-server.node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the media-nodejs@0.96.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-09-05T06_04_28_748Z-debug.log

**Comment by murillo128** [comment]
you have to init the git submodules
