### ISSUE TITLE
medooze mcu

### ISSUE THREAD

**Issue by huseyindoru** [medooze/media-server-node#167]
I use this  https://github.com/medooze/media-server-node

but I could not find an example about mcu in documents and examples

What should I do to use mcu?

		const incomingStream = transport.createIncomingStream(offered);

				const outgoingStream  = transport.createOutgoingStream({
					audio: false,
					video: true
				});
			
				const info = outgoingStream.getStreamInfo();
				connection.transporder = outgoingStream.attachTo(incomingStream)[0];
				answer.addStream(info);

and this repo is empty

https://github.com/medooze/mcu ?

**Comment by murillo128** [comment]
The mcu is a discountined product:
http://medooze.com/products/mcu.aspx

Most of the part is still inside the media server used by the SFU, but the mcu capabilities are not really used anymore.
