### ISSUE TITLE
Question:  Recorder Flushing/Chunked Audio

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#168]
Hi Sergio, 

We just come back to our internal module using medooze and are looking at adding some ongoing recording functionality. I see that medooze has this, however our use case is a little specific and we may need to write something bespoke.

We need to be able to record to files in regular chunks (say every X seconds) of a long ongoing stream. These files should be able to be stitched back together for playback later on.

I noticed there is a flush() method on the recorder and have took some time to experiment with it. It cannot seem to get it to output new filenames on flush, but I might be using it incorrectly. I know I could use multiple recorders but due to the async nature I suspect the audio files produced will not exactly match up.

Could you give a brief explanation of how the flush/timeShift functionality works on the recorder (or point me at a place in which it is explained)?

Cheers

**Comment by murillo128** [comment]
flush is only used with the timeshift feature. This allows to have a configured amount of media on memory (last minute for example) and then flush it to disk and start recordong.

chunked audio recording is not supported.

**Comment by dt-atkinson** [comment]
Thanks, are there any plans to be able to expose RTP packet information to Node.js?

**Comment by murillo128** [comment]
exposing the rtp packets to js would kill performance, instead there is an undocumented option to create a udp capturer on the transport:

https://github.com/medooze/media-server/blob/master/include/DTLSICETransport.h#L79

You can create a native module with one object that overloads that interface and pass it as first parameter of the Transport.dump() method.

However, it is not documented or I have an example I can share.

**Comment by dt-atkinson** [comment]
Very interesting, thank you sergio thats super helpful.

Right now I'm creating a streamer and then capturing the UDP separately on a nodejs udp socket, so this could be more robust solution longer term.

I wonder if capturing the RTP streamer packets separately is better or worse for performance. In my slightly naive view, I would think that passing the packets to nodejs through bindings (memory) is more performant than doing the same thing through sockets? I would assume its more performant since it wont have to traverse the OS and just map through memory.

If I try this and get it working in the node bindings are you interested in a merge PR or is it something you'd rather keep deliberately obscured?

**Comment by murillo128** [comment]
The idea is to be able to create a different project and use the object from the other project with the default media server, so each one can implement their own stuff on their own.

**Comment by dt-atkinson** [comment]
Ah I see thanks for the explanation, I'll have a dig around
