### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by eduveks** [medooze/media-server-node#170]
I am unable to install with Ubuntu 20.04 and Node v12.16.3...

Pre install commands:
```
sudo apt-get install build-essential
npm install -g node-gyp
npm install
```

Error:
`make: *** [medooze-media-server.target.mk:266: Release/obj.target/medooze-media-server/src/media-server_wrap.o] Error 1`

My package.json:

```
  ...
  "dependencies": {
    "medooze-media-server": "^0.100.0",
    ...
  }
}
```

But with Node v10 or v8 is possible to install without errors.

**Comment by murillo128** [comment]
see https://github.com/medooze/media-server-node/issues/80
