### ISSUE TITLE
one-to-one video call

### ISSUE THREAD

**Issue by farizyoga** [medooze/media-server-node#171]
hello, is there any example of using this media server to do one to one video call?

i tried emit offer event from client 1 to media server, and media server emit answer to client 2, but theres no luck the video not showing, but ontrack event called
but if i emit answer to self (client 1) the video showing

could someone help me?

thank you

**Comment by murillo128** [comment]
Please, start a discussion instead https://github.com/medooze/media-server-node/discussions
