### ISSUE TITLE
Is Plain RTP broadcasting able to stream more than one video source (through port 5004) ?

### ISSUE THREAD

**Issue by langorn** [medooze/media-server-node#175]
I try the broadcast demo, it works well.....
But, what if i need to broadcast more than one video in same medooze server. 
is that possible ?

Or i need to generate sdp instead of through the rtp port ?
or only way is create more medooze server instance ?

I cannot found any related topic , i am quite surprise no anyone got this kind of requirement.

the ffmpeg command i use
ffmpeg -rtsp_transport tcp -i 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov' -c:v copy -an -f rtp rtp://192.168.18.11:5004

I try to use 
ffmpeg -rtsp_transport tcp -i 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov' -c:v copy -an -f rtp rtp://192.168.18.11:5004/stream1
, but it dont seems the correct way to do it .

**Comment by murillo128** [comment]
the demo only creates one RTP session,  you would need to create as many as needed:

https://github.com/medooze/media-server-demo-node/blob/master/lib/broadcast.js#L27

**Comment by langorn** [comment]
oh....got it....
wow...that's so simple....

thanks for reply...
