### ISSUE TITLE
mp4 recorder  video is black

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#18]
hi:

i am testing media-server-node's recording.  it seems the video is always black.

i am useing the latest  media-server-node  and   demo code from  https://github.com/medooze/media-server-demo-node.

the ffplay info shows

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff2f0022800] Unsupported VP Codec Configuration box version 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff2f0022800] Could not find codec parameters for stream 0 (Video: none (vp08 / 0x38307076), none, 640x480, 1016 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Thu Feb 01 2018 15:52:58 GMT+0800 (CST).mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2018-02-01T07:52:58.000000Z
  Duration: 00:00:46.27, start: 0.000000, bitrate: 1089 kb/s
    Stream #0:0(und): Video: none (vp08 / 0x38307076), none, 640x480, 1016 kb/s, 14.27 fps, 90k tbr, 90k tbn, 90k tbc (default)
    Metadata:
      creation_time   : 2018-02-01T07:52:59.000000Z
      encoder         : VPC Coding
    Stream #0:1(und): Data: none (rtp  / 0x20707472), 41 kb/s
    Metadata:
      creation_time   : 2018-02-01T07:52:59.000000Z
    Stream #0:2(und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 31 kb/s (default)
    Metadata:
      creation_time   : 2018-02-01T07:52:59.000000Z
    Stream #0:3(und): Data: none (rtp  / 0x20707472), 12 kb/s
    Metadata:
      creation_time   : 2018-02-01T07:52:59.000000Z
No codec could be found with id 0

```

**Comment by murillo128** [comment]
Could you send me a mp4 file sample to check?

Which player are you using for playback? Vp8 in mp4 is quite recent and not
widely supported. Test with vlc 3.0 nightly build.

**Comment by notedit** [comment]
i  am using ffplay to play the mp4 file.

i just upload the mp4 file to https://github.com/notedit/mediaserver-test  

thanks,  i will test h264.

**Comment by murillo128** [comment]
works fine with vlc

**Comment by murillo128** [comment]
![image](https://user-images.githubusercontent.com/1070835/35671038-787f079e-073a-11e8-9011-972358268078.png)

**Comment by notedit** [comment]
yes,  vlc 3.0 works fine,  i see my ugly face.  😩 .

so  will we will support ffmpeg?  ffmpeg is widely used.

**Comment by murillo128** [comment]
I think that the question is the other way around, when will ffmpeg support vp8 on mp4?  ;)

it is quite strange it is not supported by ffmpeg already.

This has worked for me:

```
ffplay.exe c:\Users\Sergio\Downloads\x.mp4 -vcodec vp8
```

**Comment by murillo128** [comment]
created ticket on ffmpeg:

https://trac.ffmpeg.org/ticket/7000#ticket

**Comment by murillo128** [comment]
FWIW: VP8 MP4 patch landed in ffmpeg:

http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=f7aacf4ab7654a57408d5c0f871fd3b39930c6d7
