### ISSUE TITLE
Support VP9 recording

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#19]
hi:

i am testing record feature,  use this https://github.com/medooze/media-server-demo-node  

i change to video codec to  vp8/vp9/h264,  the vp8/h264 works fine.   vp9 record file just hundreds bytes.

chrome version : Version 63.0.3239.132 (Official Build) (64-bit)
mac os: 10.13.3

**Comment by murillo128** [comment]
Yes, vp9 is yet not supported, I will try to get it working today or early next week.
