### ISSUE TITLE
Can't install on Mac OS 13.0.1 

### ISSUE THREAD

**Issue by wolf-mik** [medooze/media-server-node#197]
> netlink@0.2.4 install /Users/mik/Workspace/media-server/node_modules/netlink
> node-gyp-build

  CXX(target) Release/obj.target/netlink_binding/src/binding.o
../src/binding.cc:2:10: fatal error: 'linux/netlink.h' file not found
#include <linux/netlink.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/netlink_binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxxxx/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/Users/mik/.nvm/versions/node/v12.22.12/bin/node" "/Users/mik/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mik/Workspace/media-server/node_modules/netlink
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> medooze-media-server@0.127.2 install /Users/xxxxxx/Workspace/media-server/node_modules/medooze-media-server
> test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)

  CXX(target) Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem_posix.o
  CXX(target) Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem.o
  CXX(target) Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/File.o
  CXX(target) Release/obj.

**Comment by murillo128** [comment]
The netlink dependency is in `optionalDependencies`, so the error should not cause any harm, could you paste the rest of the log?

**Comment by wolf-mik** [comment]
Thanks for the info, but I fixed the issue, it was because of my machine arch

**Comment by bakoushin** [comment]
I have similar problem on macOS 13.2.1 (Intel Mac).
Node 
In addition to `linux/netlink.h` error already mentioned I'm getting these:
```
../media-server/src/ActiveSpeakerMultiplexer.cpp:80:85: error: cannot pass object of non-trivial type 'RTPIncomingMediaStream::shared' (aka 'shared_ptr<RTPIncomingMediaStream>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
        Debug("-ActiveSpeakerMultiplexer::AddIncomingSourceGroup() [incoming:%p,id:%d]\n", incoming, id);
                                                                                           ^
../media-server/src/ActiveSpeakerMultiplexer.cpp:99:82: error: cannot pass object of non-trivial type 'RTPIncomingMediaStream::shared' (aka 'shared_ptr<RTPIncomingMediaStream>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
        Debug("-ActiveSpeakerMultiplexer::RemoveIncomingSourceGroup() [incoming:%p]\n", incoming);
                                                                                        ^
../media-server/src/ActiveSpeakerMultiplexer.cpp:105:89: error: cannot pass object of non-trivial type 'const RTPIncomingMediaStream::shared' (aka 'const shared_ptr<RTPIncomingMediaStream>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                Debug("-ActiveSpeakerMultiplexer::RemoveIncomingSourceGroup() async [incoming:%p]\n", incoming);
                                                                                                      ^
---SKIPPED---

../src/media-server_wrap.cxx:2565:50: error: no member named 'GetBackingStore' in 'v8::ArrayBuffer'
                                H264ToAnnexB((uint8_t*)uint8array->Buffer()->GetBackingStore()->Data(), uint8array->Buffer()->ByteLength());
                                                       ~~~~~~~~~~~~~~~~~~~~~~^
../src/media-server_wrap.cxx:15120:5: error: cannot use 'try' with exceptions disabled
    try {
    ^
../external/perfetto/perfetto.cc:42127:8: error: 'atomic_store<perfetto::ProducerEndpoint>' is unavailable: introduced in macOS 10.9
  std::atomic_store(&service_, std::move(service));
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1785:1: note: 'atomic_store<perfetto::ProducerEndpoint>' has been explicitly marked unavailable here
atomic_store(shared_ptr<_Tp>* __p, shared_ptr<_Tp> __r)
^
../external/perfetto/perfetto.cc:43581:12: error: 'atomic_load<perfetto::ProducerEndpoint>' is unavailable: introduced in macOS 10.9
      std::atomic_load(&producer->service_);
           ^
```

**Comment by mathpopo** [comment]
See [this doc](https://docs.google.com/document/d/1sTc_jRL87Fu175Holm5SV0kajkseGl2r8ifGY76G35k/edit). In short, GetContents was replaced by GetBackingStore in late 2019. Being a compatibility layer, nan [adapted to this](https://github.com/nodejs/nan/commit/2c023bd447661a61071da318b0ff4003c3858d39) in early 2020.

**Comment by mathpopo** [comment]
curl -O https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.xz
sudo cp -r node-v18.15.0-linux-x64/* /usr/local/
echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bashrc
source ~/.bashrc
node -v

**Comment by mathpopo** [comment]
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/docker/media-server-node/.npmrc Completed in 2ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm audit fix
21 verbose argv "audit" "fix" "--force"
22 timing npm:load:setTitle Completed in 0ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-03-28T07_47_26_834Z-
26 verbose logfile /root/.npm/_logs/2023-03-28T07_47_26_834Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 warn using --force Recommended protections disabled.
31 timing npm:load Completed in 16ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 2 files
34 timing command:audit Completed in 5ms
35 verbose stack Error: loadVirtual requires existing shrinkwrap file
35 verbose stack     at Arborist.loadVirtual (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:63:18)
35 verbose stack     at async Arborist.audit (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/audit.js:25:18)
35 verbose stack     at async Audit.auditAdvisories (/usr/local/lib/node_modules/npm/lib/commands/audit.js:425:5)
35 verbose stack     at async Audit.exec (/usr/local/lib/node_modules/npm/lib/commands/audit.js:409:7)
35 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
36 verbose cwd /docker/media-server-node/dist
37 verbose Linux 5.15.0-67-generic
38 verbose node v18.15.0
39 verbose npm  v9.5.0
40 error code ENOLOCK
41 error audit This command requires an existing lockfile.
42 error audit Try creating one first with: npm i --package-lock-only
43 error audit Original error: loadVirtual requires existing shrinkwrap file
44 verbose exit 1
45 timing npm Completed in 35ms
46 verbose unfinished npm timer audit 1679989646861
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /root/.npm/_logs/2023-03-28T07_47_26_834Z-debug-0.log
