### ISSUE TITLE
Using mirrored incoming stream tracks doesn't work

### ISSUE THREAD

**Issue by mbop001** [medooze/media-server-node#205]
I am creating two connections on different Endpoint objects. Trying to link an OutgoingStreamTrack from one Endpoint to an IncomingStreamTrack from the other endpoint, via a mirrored incoming stream track (see code below), results in no packets being forwarded to the outgoing connection. When I do this between tracks of the same Endpoint (again using a mirrored track) it does work. Any ideas what I may be doing wrong?
`
        const mirrored = outTrackEndpoint.mirrorIncomingStreamTrack(inTrack);
        outTrack.attachTo(mirrored);
`

**Comment by murillo128** [comment]
That should work, yes. Please enable debug/ultradebug logs and paste the output.

**Comment by mbop001** [comment]
I get a lot of these:
`
[node            ][1690542307.699][DBG]-RTPBundleTransport::Read() | ICE username not found [5f8dd029f4a544d0:/iFj}
[node            ][1690542307.712][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.732][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.734][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.735][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.735][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.753][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
[node            ][1690542307.761][DBG]-RTPBundleTransport::Read() | ICE username not found [5f8dd029f4a544d0:/iFj}
[node            ][1690542307.774][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
`

**Comment by mbop001** [comment]
Got it! It was a mistake in my code - I was calling Endpoint.getLocalCandidates() on the wrong endpoint... Now all seems to work as expected. 
Big thanks for your hint and quick response!
