### ISSUE TITLE
 Build error : call of overloaded ‘abs(double&)’ is ambiguous

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#21]
i just update my xcode to 9.3beta,  then i find build error after i update my xcode.

```

./media-server/src/remoteratecontrol.cpp:113:65: error: call to 'abs' is ambiguous
        if (hypothesis!=OverUsing && (fmin(fpsCalc.GetAcumulated(),60)*std::abs(off...
                                                                       ^~~~~~~~
/usr/include/stdlib.h:137:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:111:44: note: 
      candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {re...
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:113:44: note: 
      candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {re...
                                           ^
../media-server/src/remoteratecontrol.cpp:119:7: error: call to 'abs' is ambiguous
                if (std::abs(residual)<3*sqrt(varNoise))
                    ^~~~~~~~
/usr/include/stdlib.h:137:6: note: candidate function

```

**Comment by notedit** [comment]
0.20.0   works fine

**Comment by murillo128** [comment]
Can you check if replacing `std::abs` by `std::fabs` solves the issue? I cannot reproduce it localy

**Comment by notedit** [comment]
@murillo128 

i change  remoteratecontrol.cpp

```
#include <math.h>  
```

to 

```
#include <cmath>  
```

fix this problom.   thanks  


ps:  can you have a look on https://github.com/medooze/media-server-demo-node/issues/7
i can not make raw rtp input work.

**Comment by murillo128** [comment]
thanxs! commited, will push new version next week and check the other issue

**Comment by murillo128** [comment]
cmath not found on ubuntu, can you try with the std::fabs?

**Comment by notedit** [comment]
can not find fabs on mac  

```
error: no member named 'fabs' in namespace
      'std'
```

**Comment by notedit** [comment]
i mean  <cmath>  not  <cmath.h>

**Comment by murillo128** [comment]
This should work.. 

https://godbolt.org/g/bMJ6nv

could you confirm which clang version does the xcode use?

**Comment by murillo128** [comment]
Could you try latest version and check if works for you? (sorry but I don't have other way of reproducing the issue)

**Comment by notedit** [comment]
does not work.   can not find  std:fabs  

clang version: clang-6.0

`#include  <cmath>`   works

**Comment by murillo128** [comment]
Could you try to compile latest master head?

**Comment by notedit** [comment]
build ok now,  thanks

**Comment by murillo128** [comment]
pushing new ver then, thank you all for your patience!
