### ISSUE TITLE
error: call of overloaded ‘abs(double&)

### ISSUE THREAD

**Issue by sunnybear** [medooze/media-server-node#23]
# npm i --save medooze-media-server
gives
9915 warn enoent ENOENT: no such file or directory, open '/root/package.json'
9916 verbose enoent ENOENT: no such file or directory, open '/root/package.json'
9916 verbose enoent This is most likely not a problem with npm itself
9916 verbose enoent and is related to npm not being able to find a file.
9917 warn root No description
9918 verbose If you need help, you may report this error at:
9918 verbose     <https://github.com/npm/npm/issues>
9919 warn root No repository field.
9920 verbose If you need help, you may report this error at:
9920 verbose     <https://github.com/npm/npm/issues>
9921 warn root No README data
9922 verbose If you need help, you may report this error at:
9922 verbose     <https://github.com/npm/npm/issues>
9923 warn root No license field.
9924 verbose If you need help, you may report this error at:
9924 verbose     <https://github.com/npm/npm/issues>
9925 verbose stack Error: medooze-media-server@0.27.2 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
9925 verbose stack Exit status 1
9925 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
9925 verbose stack     at emitTwo (events.js:106:13)
9925 verbose stack     at EventEmitter.emit (events.js:191:7)
9925 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
9925 verbose stack     at emitTwo (events.js:106:13)
9925 verbose stack     at ChildProcess.emit (events.js:191:7)
9925 verbose stack     at maybeClose (internal/child_process.js:920:16)
9925 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
9926 verbose pkgid medooze-media-server@0.27.2
9927 verbose cwd /root
9928 error Linux 3.10.0-693.el7.x86_64
9929 error argv "/usr/bin/node" "/usr/bin/npm" "i" "--save" "medooze-media-server"
9930 error node v6.12.3
9931 error npm  v3.10.10
9932 error code ELIFECYCLE
9933 error medooze-media-server@0.27.2 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
9933 error Exit status 1
9934 error Failed at the medooze-media-server@0.27.2 install script 'test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)'.
9934 error Make sure you have the latest version of node.js and npm installed.
9934 error If you do, this is most likely a problem with the medooze-media-server package,
9934 error not with npm itself.
9934 error Tell the author that this fails on your system:
9934 error     test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)
9934 error You can get information on how to open an issue for this project with:
9934 error     npm bugs medooze-media-server
9934 error Or if that isn't available, you can get their info via:
9934 error     npm owner ls medooze-media-server
9934 error There is likely additional logging output above.
9935 verbose exit [ 1, true ]

**Comment by murillo128** [comment]
duplicated of #21

**Comment by sunnybear** [comment]
Current git code doesn't work. Can't understand why it's 'closed'

**Comment by murillo128** [comment]
because it is a duplicated issue of #21 which is still open.  I am working on it, and hope to have a fix soon.

Please check #21

**Comment by sunnybear** [comment]
ok, thx :) haven't checked open issues
