### ISSUE TITLE
[question]how can i  write my custom MediaFrame:Listener?

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#24]
i  see there is  MediaFrame:Listener,  mp4recorder implement it,  can we write custom MediaFrame:Listener?  

i think it is doable, but i see your comment in here https://github.com/medooze/media-server-node/issues/7.

i know little about swig,  but i know  node addon api can do c++/node callback.

**Comment by notedit** [comment]
i see the callback code in here  https://github.com/medooze/media-server-node/blob/master/lib/Transport.js#L74

i think it is doable,  i will try to give a test.

**Comment by notedit** [comment]
blocked by  https://github.com/swig/swig/pull/968

**Comment by murillo128** [comment]
there this, it has the PR to make it work under node 8/9
https://github.com/medooze/swig

**Comment by notedit** [comment]
yes,  i use this PR https://github.com/swig/swig/pull/968

**Comment by notedit** [comment]
i can  get the media frame callback now.    thanks @murillo128
