### ISSUE TITLE
recording mp4 file Visual Size

### ISSUE THREAD

**Issue by laowangnj** [medooze/media-server-node#25]
some tools report video in the recording file "Visual Size 16 x 2560", 
actually "640x480"

**Comment by murillo128** [comment]
which tools?

**Comment by laowangnj** [comment]
such as vlc(mediainfo). 
"Width                                    : 16 pixels
Original width                           : 640 pixels
Height                                   : 2 560 pixels
Original height                          : 480 pixels"

**Comment by murillo128** [comment]
could you send me a sample recording?

**Comment by laowangnj** [comment]
my file recorded some other people. 
just change the simulcast demo to record all the tracks who access the url in one mp4 file.
once anyone close his brower, stop recording and save the file.

**Comment by murillo128** [comment]
The recorded is tested and works for me, so I need to understand what happens on your side

**Comment by murillo128** [comment]
good, reopen if you are able to reproduce
