### ISSUE TITLE
Why not inherit from EventEmitter?

### ISSUE THREAD

**Issue by ibc** [medooze/media-server-node#3]
In https://github.com/medooze/media-server-node/blob/master/lib/Transport.js#L171:

```js
on() 
{
	//Delegate event listeners to event emitter
	this.emitter.on.apply(this.emitter, arguments);  
	//Return object so it can be chained
	return this;
}
```

Why so complex? It's easier to just inherit from the `EventEmitter` class:

```js
class Transport extends EventEmitter
{
	constructor(foo)
	{
		super();  // Must call super() before using `this`
```

**Comment by murillo128** [comment]
because I don't want to expose the EventEmitter interface publicly, as events will only be triggered from withing same object. I prefer composition to extension.

https://medium.com/javascript-scene/the-open-minded-explorer-s-guide-to-object-composition-88fe68961bed#.e7ci26mtr

**Comment by murillo128** [comment]
Thanxs for the input anyway ;)

**Comment by ibc** [comment]
> because I don't want to expose the EventEmitter interface publicly, as events will only be triggered from withing same object.

Well, if a user calls `emit()` on your exposed public class/object, he deserves hell (he could also call `transport.emitter.emit('close');`...).

However, by non exposing the `EventEmitter` interface you are hiding **useful** API such as `removeEventListener()`, `once()`, etc.
