### ISSUE TITLE
 Renegotiation after addStream  can not  publish new stream

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#32]
Hi:

I have one use case,  One user join the room without the media first,  Just receive other's media. After a while  this use want to publish his media to the room,   I just do a  renegotiation after this user addStream,  It seems renegotiation can not publish this new stream.

I write one demo to produce this.   https://github.com/notedit/webrtcon-2018-workshop/tree/master/mediaserver

One user join a room without media,  after two seconds he add stream and  renegotiate.   chrome://webrtc-internal does not show send tracks.

**Comment by murillo128** [comment]
Is the problem on the browser or on the media server?

**Comment by notedit** [comment]
I think it is a problem on the media server.  

we do the same thing with other mediaservers(mediasoup, janus-gateway) before, they works well.

**Comment by notedit** [comment]
I did some test,  it seems media server does not support renegotiate.  

If i have one stream,  renegotiation will stop that stream too.

**Comment by murillo128** [comment]
What do you mean by renegotiation?

**Comment by murillo128** [comment]
I mean, what are you changing between the offer/answers?

**Comment by notedit** [comment]
does not change anything.    After browser connect the media server,   then do another offer/answer ,  the sending stream will stop.

**Comment by notedit** [comment]
My bad,  renegotiation will not stop stream.    but  renegotiation still can not publish new add stream.
@murillo128  can you point me some direction?  i want to do some dig.

**Comment by notedit** [comment]
I just fixed this.   when  offer with no media, the  offer direction is recvonly,  so the answer is sendonly.
reoffer will change that.  so i change the direction to sendrecv on server side when the first offer.  
that fix this.
