### ISSUE TITLE
one-to-many broadcast

### ISSUE THREAD

**Issue by Shion093** [medooze/media-server-node#37]
It is possible with this library to create a broadcast that takes my webcam feed and streams it across multiple browsers?

If so, can someone give me a few hints.

I've already tried modifying the demos, but I think I'm missing something

Thanks

**Comment by notedit** [comment]
it is possible to do one-to-many  broadcast.  

the publisher side  do addStream and join the room,   the viewer does not do getUserMedia and addStream  then join the room.

**Comment by murillo128** [comment]
as @notedit just modify the the demos so you attach the incoming stream from one endpoint to the outgoing streams created on the other viewer endpoints

**Comment by murillo128** [comment]
Also, please, for question about usage better use the mailing list on the google groups
