### ISSUE TITLE
Add new stream to existing connections

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-node#39]
Great package!
How to add a new stream to already established connection (after SDP answer)?
Thanks in advance!

**Comment by murillo128** [comment]
You can add both input/output streams once you have negotiated the dtls/ice/rtp properties. You would need to renegotiate the SDP on the client side:

https://github.com/medooze/sfu/blob/master/lib/Participant.js#L111

Note that the preferred method for multistream is still plan B (although unified is also supported). I am still waiting to have mature support for transceivers on chrome before migrating.

For further questions, please ask them on the forum:

https://groups.google.com/forum/#!forum/medooze
