### ISSUE TITLE
Add "disconnected" event on DTLS shutdown at Transport

### ISSUE THREAD

**Issue by murillo128** [medooze/media-server-node#42]

**Comment by notedit** [comment]
great feature,  sometimes  we can not depend on signaling

**Comment by pal-dtatkinson** [comment]
Is it worth/easy to add establishing/established also?

**Comment by murillo128** [comment]
done, please test it and let me know if there is any issue

**Comment by pal-dtatkinson** [comment]
On 0.64.0 I get a compile error. Fixed versions 0.64.1 -> 0.64.3 but on run I get an error:
`
dyld: lazy symbol binding failed: Symbol not found: _HMAC_CTX_init
  Referenced from: /Users/dave/IdeaProjects/streaming-sfu/node_modules/medooze-media-server/build/Release/medooze-media-server.node
  Expected in: flat namespace

dyld: Symbol not found: _HMAC_CTX_init
  Referenced from: /Users/dave/IdeaProjects/streaming-sfu/node_modules/medooze-media-server/build/Release/medooze-media-server.node
  Expected in: flat namespace
`

**Comment by murillo128** [comment]
can you open a new issue, please?

Also, could you check if you have upgraded node in the meanwhile? I think they have upgraded bundled openssl versions and that may be causing some issues

**Comment by pal-dtatkinson** [comment]
Urgh sorry - my bad. You were right, I had mismatched node versions. Running now and testing.

**Comment by pal-dtatkinson** [comment]
I'm seeing connected and closed events. I haven't seen any connecting or failed (not sure in which scenarios they would occur). 

If I hang the connection (client doesn't tell us they are going away) I never get the closed event. I presume this is expected and related to #43.

**Comment by murillo128** [comment]
I think that `new` and `connecting` are "fired" before the transport obejct is returned, so you will be able to the the state from the object, but not the event. I don't expect to see any `failure` normally.

**Comment by pal-dtatkinson** [comment]
In that case I believe all is working as expected from my side :)
