### ISSUE TITLE
can not negotiate video  well with iOS SDK 

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#44]
I am working on a iOS SDK wrapper that talks to  media-server.

audio can works well,  media-server can receive the audio,  but video fails.

I have tried vp8 and h264,  they failed both.   then i did some test.

1,  the media-server side code keep the same.

I write some  brower code to test,  the brower code  can send video and audio correctly.
the iOS SDK code can only send audio,  video fails. ( I am sure the iOS SDK support vp8/h264 both).

2,  the iOS SDK code keep the same.

I write  another server side code with aiortc, https://github.com/jlaine/aiortc ,  logic is the same with media-server-node,  just exchange offer/answer.  the aiortc can receive audio/video correctly.
the media-server code just can receive audio.

so  I think media-server-node generate sdp does not works well with iOS SDK.

here is some offer/answers.

iOS SDK  talks  to  aiortc , offer from iOS SDK 
https://gist.github.com/notedit/7955449fa9f55dd92ad47e40b1cba9b0

iOS SDK  talks  to  aiortc , answer from aiortc
https://gist.github.com/notedit/bef0a6e805d3d1aa9fa7e9e5e224fcf8

iOS SDK  talks  to media-server-node , offer from iOS SDK 
https://gist.github.com/notedit/ca37fda811fb835f69413db99d23688e

iOS SDK  talks  to media-server-node ,answer  from  media-server-node
https://gist.github.com/notedit/6844b7a042c6720f275051ce3e7b5a7c

**Comment by notedit** [comment]
I can provide the whole test code  if you have iOS devices.

**Comment by notedit** [comment]
The media-server capabilities

```
const Capabilities = {
	audio : {
		codecs		: ["opus"],
		extensions	: [ "urn:ietf:params:rtp-hdrext:ssrc-audio-level", "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"]
	},
	video : {
		codecs		: ["vp8"],
		rtx		: true,
		rtcpfbs		: [
			{ "id": "transport-cc"},
			{ "id": "ccm", "params": ["fir"]},
			{ "id": "nack"},
			{ "id": "nack", "params": ["pli"]}
		],
		extensions	: [ "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"]
	}
};
```

**Comment by murillo128** [comment]
Does the iOS SDK rejects the SDP answer or do you get any visible error? Can you get a network capture (or a dump on the Endpoint object) to check if it is sending video at all? Also, can you check the iOS SDK is able to receive it?

**Comment by notedit** [comment]
the iOS SDK peerconnection setRemote answer without error.  

it does not send video,  i can see the info in xcode(the cpu usage and network sending/receiving )

it can receive remote vp8 video and play.  so  it is really strange.

**Comment by notedit** [comment]
I have spend two days on this issuse.  If anyone came to this issuse  please let me know.

**Comment by notedit** [comment]
After  several days,  I figure out finally,   the native code need "VP8" codec,  not  "vp8" codec.
