### ISSUE TITLE
Recorder can not record audio only track

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#45]

**Comment by murillo128** [comment]
Indeed.

By default, Recorder wait for first Iframe before starting to record media.

It is possible to change this behavior by changing to 

```
this.recorder.Record(false);
``` 
in https://github.com/medooze/media-server-node/blob/master/lib/Recorder.js#L22

I will add it to the `params`  as sson as I am able to test it properly (OOO currently)
