### ISSUE TITLE
Ability to add track to the stream

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-node#48]
Would be great to have interface to add single track to existing stream

**Comment by notedit** [comment]
you can add your single track  from this line  https://github.com/medooze/media-server-node/blob/master/lib/IncomingStream.js#L155

**Comment by murillo128** [comment]
I am thinking in adding a CreateIncomingTrack to Transport (same as it is done for output stream tracks) and an addTrack to the stream object. 

What do you think?

**Comment by tomas-berg** [comment]
@murillo128 Would be great.

**Comment by murillo128** [comment]
I have added individual track creation (on stream and transport) and addTrack on streams, please check it out.
