### ISSUE TITLE
Safari 12 crashes on peer connection.

### ISSUE THREAD

**Issue by igrooves** [medooze/media-server-node#49]
I know you don't specifically quote that you do support safari, or edge for that matter. But the reason i use this software is to fulfil the missing MediaStreamRecorder api on these browsers.

Safari 11 worked perfectly, however 12, on mac and iOS now crashes when a peerconnection is established. I have narrowed this down to the media server, and i think i may have something to do with the codec offered. This doesn't occur establishing a connection between 2 peers natively.

This can be replicated using the https://github.com/medooze/media-server-demo-node record demo.

This also occurs on the beta / preview safari.

**Comment by murillo128** [comment]
can you try with latest version?

**Comment by igrooves** [comment]
The issue seems resolved. I don't know if this is prevalent, but i did resolve it on 0.45 manually selecting the h264 codec. As safari only has this codec it seems strange.
