### ISSUE TITLE
Add Mac OSX support

### ISSUE THREAD

**Issue by stringa** [medooze/media-server-node#5]
I tried just pulling down this library to try it out, and on my macbook I get a lot of errors revolving around the compilation of some mp4 library. Is this expected? Do I need to be on debian or some other os?

> 
> In file included from ../external/mp4v2/lib/src/atom_mdat.cpp:22:
> In file included from ../external/mp4v2/lib/src/impl.h:6:
> In file included from ../external/mp4v2/lib/src/src.h:28:
> ../external/mp4v2/lib/src/mp4util.h:36:51: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
>             throw new Exception("assert failure: "LIBMPV42_STRINGIFY((expr)), __FILE__, __LINE__, __FUNCTION__ ); \
>                                                   ^
>                                                    
> ../external/mp4v2/lib/src/mp4util.h:58:9: error: cannot use 'throw' with exceptions disabled
>         throw new PlatformException("malloc failed",errno,__FILE__,__LINE__,__FUNCTION__);
>         ^
> ../external/mp4v2/lib/src/mp4util.h:82:9: error: cannot use 'throw' with exceptions disabled
>         throw new PlatformException("malloc failed",errno,__FILE__,__LINE__,__FUNCTION__);
>         ^
> In file included from ../external/mp4v2/lib/src/atom_mdat.cpp:22:
> In file included from ../external/mp4v2/lib/src/impl.h:6:
> In file included from ../external/mp4v2/lib/src/src.h:29:
> ../external/mp4v2/lib/src/mp4array.h:124:1: error: cannot use 'throw' with exceptions disabled
> MP4ARRAY_DECL(MP4Integer8, uint8_t)
>

**Comment by murillo128** [comment]
OSX is yet not supported. It is in my TODO list as soon as I am able to get access to an OSX build environment (I am not a mac user myself). 

Any help would be appreciated.

**Comment by stringa** [comment]
What environment does this work on?

**Comment by murillo128** [comment]
Verified on Ubuntu, should work on any Linux with new GCC

**Comment by stringa** [comment]
I've been trying to put together a docker container for this, but for some reason I still can't get it to compile...I still get gcc compiler errors....


# Node.js app Docker file

FROM ubuntu:14.04
MAINTAINER Thom Nichols "thom@thomnichols.org"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -qq update

RUN sudo apt-get install build-essential --assume-yes
RUN sudo apt install git --assume-yes
RUN sudo apt-get install curl --assume-yes

RUN apt-get install -y python python-dev python-setuptools

RUN curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

RUN npm install -g yarnpkg
# TODO could uninstall some build dependencies

# fucking debian installs `node` as `nodejs`
RUN update-alternatives --install /usr/bin/node node /usr/bin/nodejs 7
RUN apt-get install -y software-properties-common
RUN apt-get install -y python-software-properties

RUN sudo add-apt-repository ppa:ubuntu-toolchain-r/test
RUN sudo apt-get update
RUN sudo apt-get install gcc-6 g++-6 --assume-yes
RUN sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 1 --slave /usr/bin/g++ g++ /usr/bin/g++-6

VOLUME ["/data"]

ADD . /data
RUN cd /data && npm install

EXPOSE 3000
EXPOSE 8080
EXPOSE 8443

WORKDIR /data

CMD ["yarn", "start"]

**Comment by stringa** [comment]
So the docker file above shows an Ubuntu container with gcc and g++ 6 running. I'm not sure why it still doesn't compile properly. Wondering if you can give me some hints

**Comment by murillo128** [comment]
I am using 16.04 but should work on your set up.

Would you mind to open a new issue with the compiler errors?

I will try to reproduce your environment and see if I can make it fail also.
