### ISSUE TITLE
RTPBundleTransport Error

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-node#53]
When stopping working outgoing stream I get:
`[0x7f9df37fe700][1542091053.038][ERR]-RTPBundleTransport::ReadRTP() | No registered ICE candidate for [127.0.0.1:35280]`

So, connection is okay, btw. Above error is not on regular basis.
1. Is it really ICE problem?
2. How do we process single ice messages?
3. Stream remains active (Google Chrome) - no inactive callback was called on client side.

Thanks.

**Comment by murillo128** [comment]
This happens if an rtp packet is received form an ip:port which has not 
been registered with an ICE stun request, so the medias server cannot 
route it to the appropriate transport.

Does it happen at the beginning (before the transport is initialized) or 
at the end (when transport is closed, but pc is not yet on browser) or 
in the middle of a call?

Best regards
Sergio

**Comment by tomas-berg** [comment]
@murillo128 Sergio thanks for reply.
This happens after we stop stream and close transport for peer. Browser already is closed at this moment.

**Comment by murillo128** [comment]
There may be a few rtp packets flying around, should not happen after PC 
is really closed.

I can reduce the log level to Debug so it doesn't spawn the log.

**Comment by tomas-berg** [comment]
@murillo128 ok, got it, thanks

**Comment by tomas-berg** [comment]
@murillo128 btw, sometimes Google Chrome keeps stream in active state (no inactive callback was called), even after we stopped it on server and delete transport.

**Comment by murillo128** [comment]
You have to signal it back from the server to the client and perform an sdp O/A to remove the stream on the browser.

By the way, I have just released a client lib for browers, maybe it is helpful to you:

https://github.com/medooze/media-server-client-js

**Comment by murillo128** [comment]
can I close this?

**Comment by tomas-berg** [comment]
@murillo128 , yes, please
