### ISSUE TITLE
Firefox multiple track ids

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-node#55]
When trying to recevie two streams on Firefox v63 I get:
> InvalidSessionDescriptionError: Found multiple different webrtc track ids in m-section 0. The behavior here is undefined.

Google Chrome works perfectly.

**Comment by murillo128** [comment]
Note that firefox supports unified plan, while chrome uses plan-b yet. The SDPInfo is by default plan-b, you can do unified plan by calling sdp.unify().

This has several limitations as for example the sfu sdp has to be an offer and it can't be renegotiated (i.e. only add or remove tracks).

For proper unified plan support I would recommend to use the media server client js lib.
