### ISSUE TITLE
Getting Ubuntu working

### ISSUE THREAD

**Issue by stringa** [medooze/media-server-node#6]
So, I'm running parallels now with Ubuntu 16.04 with GCC 6 and Node 6.9.2. I've got everything downloading and building, but now when I actually goto actually require the MediaServer

`const MediaServer = require('medooze-media-server');`

I get the following error.

```
stringa@ubuntu:/media/psf/development/media-server-test$ npm run server

> media-server-test@0.1.0 server /media/psf/development/media-server-test
> node server/main.js

module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/medooze-media-server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/media/psf/development/media-server-test/node_modules/medooze-media-server/lib/MediaServer.js:4:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/home/stringa/.nvm/versions/nod


```

I see that there is no /Release folder that it is trying to reference from the library even though NPM ran find...

![screen shot 2017-04-27 at 8 47 26 pm](https://cloud.githubusercontent.com/assets/1191141/25513561/c8b8cc9a-2b8a-11e7-81f6-e125dcf0d3c5.png)

![screen shot 2017-04-27 at 8 36 12 pm](https://cloud.githubusercontent.com/assets/1191141/25513339/4afc05a2-2b89-11e7-9a8f-018913f74e32.png)

**Comment by stringa** [comment]
Just tried with node 7.9.0 also, and I get the same error. if this is not obvious, I would love to get a few minutes with you to get this thing up and running. If maybe we could skype,  my skype id is: facebook:sstringa (I will delete this as soon as you respond). I'm in Seattle and if I can get this working and show a good demo, it could get adopted.

I would love to hear back from you...

**Comment by murillo128** [comment]
can you check with latest npm version?

**Comment by murillo128** [comment]
closed due to timeout.. ;)

Please reopen if you have tested and it still fails
