### ISSUE TITLE
Medooze for windowzzzzz

### ISSUE THREAD

**Issue by imalyavskiy** [medooze/media-server-node#60]
Hello guys! Is there any plans to add windows support by you coolest media server? 
I just tried to build it and, of course got errors and  figured out that the best way to made medooze running on both Win and Linux and keep the code clean is to use boost.
Any thoughts about this?

**Comment by murillo128** [comment]
There are no plans to include Windows support (boost is a no-go), however, it should run in the Linux Subsystem Windows (the ubuntu shell). Would be worthy if you give it a try.

**Comment by imalyavskiy** [comment]
Thank you for the answer. But could you please explain your 'no go' for the boost?

**Comment by murillo128** [comment]
media server package is self contained, don't want to include the 157MBs of boost in it so ti can be compiled.

**Comment by imalyavskiy** [comment]
OK let it be self contained then - e.g. std::thread?

**Comment by murillo128** [comment]
indeed, but original  code was pre std::thread, will be rewritten eventually.
