### ISSUE TITLE
CPU usage too much  when use the sdpmanager. 

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#63]
Hi @murillo128 

I am testing your sdpmanager.  the cpu useage will  reach 300% when  plan-b and unified plan use together.

test demo:
https://github.com/notedit/sdpmanager-playground

How to Reproduce:

open  https://xxxxx:8000/  add three unified stream.
then open  https://xxxxxx:8000/planb.html, watch the  stream  will show this.

**Comment by notedit** [comment]
Update to the latest version fix this.   sorry.

**Comment by murillo128** [comment]
the curious thing is that it shouldn't affect if you are not using h264 .. will have to investigate further..
