### ISSUE TITLE
Build failure with 0.56.0

### ISSUE THREAD

**Issue by Nicholi** [medooze/media-server-node#64]
Pretty obvious error, one of the new submodules (libav and friends) wasn't pushed I guess? No errors reverting to 0.55.5

> In file included from ../media-server/src/DTLSICETransport.cpp:40:0:
> ../media-server/src/aac/aacencoder.h:12:10: fatal error: libavcodec/avcodec.h: No such file or directory
>  #include <libavcodec/avcodec.h>
>           ^~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> medooze-media-server.target.mk:228: recipe for target 'Release/obj.target/medooze-media-server/media-server/src/DTLSICETransport.o' failed
> make: *** [Release/obj.target/medooze-media-server/media-server/src/DTLSICETransport.o] Error 1
> make: Leaving directory '/opt/millicast/webrtc-cdn-viewer/node_modules/medooze-media-server/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> gyp ERR! System Linux 4.15.0-43-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
> gyp ERR! cwd /opt/millicast/webrtc-cdn-viewer/node_modules/medooze-media-server
> gyp ERR! node -v v10.14.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm WARN webrtc-cdn-viewer@1.0.0 No description
> npm WARN webrtc-cdn-viewer@1.0.0 No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! medooze-media-server@0.56.0 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the medooze-media-server@0.56.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nicholi/.npm/_logs/2019-01-18T23_03_42_358Z-debug.log
>

**Comment by murillo128** [comment]
it was a wrong include, this version may be a bit unstable (change is quite deep) so better not use it on prod for now.
