### ISSUE TITLE
Is there a way to get access to the rtp data?

### ISSUE THREAD

**Issue by lylepratt** [medooze/media-server-node#7]
I browsed through the docs, but didn't see an obvious answer for this:
Is there a way to get access to the RTP data as it is coming through a "Streamer"? Basically, I need to be able to decode the RTP frame and get access to each PCMA chunk of data.

**Comment by murillo128** [comment]
no, currently it is not possible., as there are yet not a callback mechanism from c++ to js.

What would you do later on with the pcma data? I was thinking in exposing also the audio coding/decoding functions already available on the media server code.
