### ISSUE TITLE
Does medooze re-encode outgoing rtp stream internally when incoming stream attached?

### ISSUE THREAD

**Issue by tkmn0** [medooze/media-server-node#72]
As title, I wonder medooze re-encodes rtp stream or not.

If medooze re-encodes, How can I handle some options (e.g. keyframe interval, quantizer) for each tracks?

Best regards.

**Comment by murillo128** [comment]
No, no transcoding is performed on server side.

**Comment by tkmn0** [comment]
Thanks for your replay :)
I see medooze does not transcode streams.

Without transcoding on server side, How does [Refresher](https://github.com/medooze/media-server-node/blob/2d2320aa3c1e0c0ddf95d5f983a2a9a039783231/lib/Refresher.js) works? 

We try to forward rtp tracks(video is h264 encoded, audio is opus encoded) to gstreamer.
Actually, we can receive rtp and paly it :)  However, sometimes video frame shows gray fogged screen..
We guess that not enough I-frame came frame medooze sfu server.

**Comment by murillo128** [comment]
Refresher request periodically an Iframe to the origin via RTCP PLI/FIR, it is specially thought to be used with the recording as you will be likely would want to seek the file to a particular location.

**Comment by tkmn0** [comment]
Thanks! 
I see how works the Refresher :)
