### ISSUE TITLE
Memory Leak on Transport Creation

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#77]
The transports I am creating are never being freed from memory from what I can tell. This is even if i stop everything... and even if I specifically call Medooze to terminate.

Perhaps I am doing something wrong?

Example code here: https://pastebin.com/4ZfQ7V1P

**Comment by murillo128** [comment]
Note the objects are freed by node garbage collector.

You can force it via: https://www.xarg.org/2016/06/forcing-garbage-collection-in-node-js-and-javascript/

**Comment by pal-dtatkinson** [comment]
Even forcing the GC didn't free the objects from the heapdump - the heapdump actually calls the GC anyway I believe!

**Comment by pal-dtatkinson** [comment]
Running the script I end up with the transports having the following Retainers in my heap dump if it's of any help:
Global Handles -> GC roots

Can you reproduce this your end?

**Comment by murillo128** [comment]
How can I run the heapdump?

**Comment by pal-dtatkinson** [comment]
I was doing it with IntelliJ by running with the v8 profiler enabled but you can do it in a few different ways:
https://medium.com/tech-tajawal/memory-leaks-in-nodejs-quick-overview-988c23b24dba

**Comment by pal-dtatkinson** [comment]
Has anyone else managed to reproduce this or is it a configuration on my system?

**Comment by murillo128** [comment]
I have tried, but got not much time and/or luck to reproduce it

**Comment by pal-dtatkinson** [comment]
Strange, I can reproduce it 100% of the time, it doesn't seem to clean up any transports via the GC.
@notedit do you have any similar experiences?

**Comment by pal-dtatkinson** [comment]
I have done a bit of digging and I believe it may be a problem around Transport.js

Lines 100:
`this.listener = new Native.DTLSICETransportListener(this);`
and 121:
`this.senderSideListener = new Native.SenderSideEstimatorListener(this);`

Creation of these objects whilst passing Transport into there as a reference might be stopping the Transport being GC'd - perhaps we need to explicitly free Transport from those native objects?

**Comment by murillo128** [comment]
the `listener` and `senderSideListener` are nullified here https://github.com/medooze/media-server-node/blob/master/lib/Transport.js#L823 and should be freed by the GC. That should remove the references to `this` and allow to collect it.

**Comment by pal-dtatkinson** [comment]
I did see that and I was under the impression that should have worked too... I am slightly out of depth here (in that I haven't written a C++ -> NodeJS bridge before).

**Comment by murillo128** [comment]
the easiest way is to add a destructor to both listeners in the c++ code and check if they are called on  GC

**Comment by murillo128** [comment]
here:
https://github.com/medooze/media-server-node/blob/master/src/media-server_wrap.cxx#L2225

add
```
~DTLSICETransportListener() { Log("Destroing DTLSICETransportListener\n"); }
```

**Comment by pal-dtatkinson** [comment]
Thank you, I'll get back to you on this

**Comment by pal-dtatkinson** [comment]
Not fully got my head around how the memory management works yet but explicit calling `Reset()` on the persistent objects within the listeners allows the GC to collect the Transports.

Are the persistent references supposed to be weak references?

https://github.com/pal-dtatkinson/media-server-node/commit/a8c84d189b3410a37c9da31aea2173dc5da5ed97

**Comment by murillo128** [comment]
I assumed that it should be released automatically:

https://github.com/nodejs/nan/blob/master/doc/persistent.md

**Comment by murillo128** [comment]
```
  /**
   * The destructor will dispose the Persistent based on the kResetInDestructor
   * flags in the traits class.  Since not calling dispose can result in a
   * memory leak, it is recommended to always set this flag.
   */
  ~Persistent();
```

**Comment by murillo128** [comment]
```
Nan::NonCopyablePersistentTraits & v8::NonCopyablePersistentTraits
Default traits for Nan::Persistent. This class does not allow use of the a copy constructor or assignment operator. At present kResetInDestructor is not set, but that will change in a future version.
```
WTF!

**Comment by murillo128** [comment]
I think that adding an alias for the Persistent template:
```
template<typename T >
using Persistent = Nan::Persistent<T,Nan::CopyablePersistentTraits<T>>;
```
And then replacing `Nan::Persistent` by `Persistent' will do the trick.

**Comment by pal-dtatkinson** [comment]
That's pretty amazing haha. Okay let me test this out...

**Comment by pal-dtatkinson** [comment]
Seems to work well doing this.

I have replaced all references to Nan::Persistent with the new template here:
https://github.com/pal-dtatkinson/media-server-node/commit/e885138ffc99418aac7f205f707ed6ee533bd88c

**Comment by murillo128** [comment]
I have added the changes in the latest commit to the swig interface file as well as other pending changes I had on the queue. Please, check it is fixed and thank you much for catching this!

**Comment by dt-atkinson** [comment]
Looks good to me, I'll run a few more test but I think we can consider this closed. 👍
