### ISSUE TITLE
add JSON Logging

### ISSUE THREAD

**Issue by maxhawkins** [medooze/media-server-node#78]
Is it possible to change the format of the logs? I'd like to emit logs as JSON so i can search them using my JSON-based logging system.

**Comment by murillo128** [comment]
not currently, the log system is inside the c++ part (only useful for debugging), the js part does not integrate any logging at all.

The app on top is free to implement any kind of logging.

**Comment by agouaillard-cosmo** [comment]
@murillo128 is it something you plan to implement and that we should keep around, or shall we close this ticket?
