### ISSUE TITLE
node 12  support 

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#80]
It seems node12 does not support swig native code.

**Comment by murillo128** [comment]
https://github.com/swig/swig/issues/1520

**Comment by murillo128** [comment]
let's keep it open, seems PR is close o be merged and testable.

**Comment by murillo128** [comment]
https://github.com/swig/swig/pull/1702

**Comment by notedit** [comment]
@murillo128  may be we could think about the napi.

https://github.com/nodejs/node-addon-api  
https://nodejs.org/api/n-api.html

**Comment by lissyx** [comment]
> let's keep it open, seems PR is close o be merged and testable.

there's already an one issue that you mentionned: https://github.com/swig/swig/issues/1520

**Comment by murillo128** [comment]
seems that swig finally supports node 12, hope to be able to fix it soon!

**Comment by murillo128** [comment]
only took two years!!! 

I will do more tests tomorrow to ensure everything is working and will release a new version.
