### ISSUE TITLE
Pause Recording On Server

### ISSUE THREAD

**Issue by kshitij199319** [medooze/media-server-node#87]
Hi Team,
I am trying to record stream via Recorder class, But it seems that it has only two instance methods
1.  record(incomingStreamOrTrack)
2. stop()
I have a requirement to pause the recording where users are allowed to pause the recording and once the  user resumes again the recording the recording should be resumed and that paused videoframe should not be included into that mp4 file since it was paused by the user and only 
recorded frames should be included into that file which will be stored on the server.

It seems that we don't have any method to pause and resume recording. 
Do we have any method that we can use to implement this functionality or any workaround that you think will suffice the requirement.

Regards,
Kshitij

**Comment by murillo128** [comment]
added mute() to recorder and recorderTrack, it is untested, so please check it and let me know the results

**Comment by kshitij199319** [comment]
Thanks @murillo128 for adding the functionality, I will surely test it and revert back to you.
Also, I want to know that how recording is saved at server end, as in it is saved in chunks or continuously streams get saved at the storage path. 
I am asking this because I have a doubt that  what will happen in case of medooze node goes down.
When I intentionally did that, a corrupt file formed on recording path but with no video..
Is there a way we can save this recording stream data in chunks or at regular interval..so that if suppose at a particular instance, one of medooze node goes down, the  video is saved till last data chunk on the server.
Is is possible to handle this fault tolerance or is there any  other way we can handle this?

**Comment by murillo128** [comment]
the recording is done via the mp4v2 lib (https://github.com/medooze/mp4v2). My modifications only adds vp9/vp8 and opus support to it, but internal stuff is unchanged.

I think that data is stored into disk continuously, but the mpbox structure is not updated correctly until it is closed.
