### ISSUE TITLE
CPU Balloons on Endpoint Reuse

### ISSUE THREAD

**Issue by dt-atkinson** [medooze/media-server-node#90]
I realise this is a rather generic title and I'm am still investigating it - however:

I create a single `Endpoint`.

For every test iteration:
- I have a new `Streamer` which I make a `StreamerSession` from (with audio going through).
- I hook the `StreamerSession` up to a new `Transport` from the `Endpoint` from above. (transport connected)
- Wait 2 seconds
- I tear down the `Streamer`, `StreamerSession` and `Transport`

I repeat this iteration many times over the course of an hour or more and I see that the CPU is getting extremely high (up to 50% so far) for just the single connection. To make things more interesting if I stop everything there is no CPU load. As soon as I add another iteration (connection) the CPU goes back up to the same level for the connections duration.

Is there a list being iterated over in the C++ code thats not being cleared? Possibly for routing packets? Or stream information. Maybe you can point me in the right direction.

If I _recreate_ the `Endpoint` for every new iteration/connection the CPU stays within 3-4% (which is about the level the code starts at before ballooning over time). So it's seemingly something in the `Endpoint` not being cleaned/cleared. The fact that it applies for the duration of the connection routing I presume means its somewhere near stream/socket level?

Recreating the endpoint certainly feels like the wrong thing to do although it does work around my issue...

**Comment by murillo128** [comment]
Could you use https://github.com/brendangregg/FlameGraph to get cpu usage graph and check where is the cpu being used?

```
# perf record -F 99 -p 181 -g -- sleep 60
# perf script > out.perf
# ./stackcollapse-perf.pl out.perf > out.folded
# ./flamegraph.pl out.folded > kernel.svg
```

**Comment by dt-atkinson** [comment]
Sure, I'll give it a shot

**Comment by dt-atkinson** [comment]
2 minutes at 99Hz.
https://drive.google.com/file/d/1oosm8ahE8fx_AnNHqaQpRWufqD0DO4xl/view?usp=sharing

**Comment by murillo128** [comment]
The cpu is been used on the event loop. The StreamerSessions have two, but they are stopped on `RTPTransport::Stop()` called by ` RTPTransport::End()`  which is called by js `stop()`.

Can you enable logs and confirm if you see this trace? 
https://github.com/medooze/media-server/blob/master/src/RTPTransport.cpp#L613

**Comment by dt-atkinson** [comment]
Can confirm I can see that trace yes

**Comment by murillo128** [comment]
the only other objects that uses even loops are the EmulatedTransport, Transport and the MP4 player, are you using any of them too?

**Comment by dt-atkinson** [comment]
Just Endpoint

**Comment by murillo128** [comment]
are you stopping them properly?

**Comment by dt-atkinson** [comment]
They don't get stopped - they are reused for the transports and an remain for the life of the application

**Comment by dt-atkinson** [comment]
Is correct practice in your view to have an endpoint per StreamerSession and transport grouping then?

**Comment by murillo128** [comment]
How were you reusing the endpoint? can you put a code snippet here?

Attaching transport belonging to different Endpoints is not as efficient as attaching between transports of the same Endpoint (due to inter thread locking). But adding too many transports on an Endpoint can cause load to not being distributed evenly between cpu processors.

**Comment by dt-atkinson** [comment]
The transport is *only* attaching to the StreamerSession (which doesn't have an Endpoint). All transports are being made on the same endpoint but each has its own StreamerSession.

Everything has stop() called except the endpoint because I was hoping to reuse that as I only create as many endpoints as I have cores on the box.

I'll try to get an example for you since I can't paste my project.

**Comment by dt-atkinson** [comment]
I haven't easily managed to reproduce this at present and have worked around the issue through recreation of the Endpoint.
