### ISSUE TITLE
Recording not working after MediaFrame refactoring

### ISSUE THREAD

**Issue by kshitij199319** [medooze/media-server-node#92]
Hi @murillo128  this is in refrence to issue #87 
After the additional code that you have added for recording, the recording is not working properly as when I tried to npm install medooze-media-server with latest version and perform the recording, the .webm file created successfully with audio codec OPUS and video codec VP9, but when I played the recording on VLC It stuck with the first frame throughout the end of recording. 
I replaced recorder.js and recorderTrack.js with the previous build files and it worked fine. 
Kindly check once into the mute code that you have added.

Regards
kshitij

**Comment by murillo128** [comment]
I have not been able to reproduce the issue, could you run the test again to see if it was a one time issue or it is 100% reproducible on your side?

**Comment by kshitij199319** [comment]
@murillo128  it was 100% reproducible on my side.

**Comment by murillo128** [comment]
should be fixed now, please update and try again.
