### ISSUE TITLE
[question] Black screen during a video call

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-node#93]
Hi Team!
Have non-systematic issues when attaching video stream from Safari(iOS) to Chrome(any system).

Have these capabilities on SFU:
```json
{
    "video" : {
            "codecs" : ["h264"],
            "rtx" : true,
            "rtcpfbs" : [
                    { "id": "goog-remb"},
                    { "id": "ccm", "params": ["fir"]},
                    { "id": "nack"},
                    { "id": "nack", "params": ["pli"]}
            ],
            "extensions": [
                    "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01",
                    "urn:ietf:params:rtp-hdrext:framemarking"
            ]
    }
}
```
Chrome peer gets just black screen some time.
What would be the case?
What are recommended capabilities or any best practices in this case?
Thanks a lot.

**Comment by tomas-berg** [comment]
Could it be about packetization mode not set or I-Frame problems?
```
level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=fmtp:121 apt=127
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=fmtp:107 apt=125
a=fmtp:125 
```

**Comment by notedit** [comment]
Do not using `urn:ietf:params:rtp-hdrext:framemarking`  with Android/iOS native sdk.

There is a bug in  H264Layer selecter.   I came to this too.  Did not dig too much yet.

**Comment by tomas-berg** [comment]
@notedit Thanks a lot. I will give it a try.

**Comment by tomas-berg** [comment]
@notedit after removing framemarking it gets more stable. But we still see black screen sometimes and a lot of freezes and artifacts.

In tests where we have Chrome (Win) and Safari (iOS) - Chrome receives very small video stream bitrate from iOS. Other platforms are OK.

@notedit How did you solve this with Android/iOS - or it's just the problem right now?

**Comment by murillo128** [comment]
> There is a bug in H264Layer selecter. I came to this too. Did not dig too much yet.

What issue? The framemarkig on chrome is still not reliable (especially for h264) so better not use it for now

**Comment by notedit** [comment]
> > There is a bug in H264Layer selecter. I came to this too. Did not dig too much yet.
> 
> What issue? The framemarkig on chrome is still not reliable (especially for h264) so better not use it for now

I am not sure it is webrtc's bug or medooze,  iOS native sdk can not talk to another client when using `framemarking` ,  i disable that for now.

**Comment by murillo128** [comment]
Seems that you are not using all capabilities for enabling transport wide cc, so remb will kick in, and it is not as in good shape as it should:

try with this:
```
const Capabilities = {
	audio : {
		codecs		: ["opus"],
		extensions	: [ "urn:ietf:params:rtp-hdrext:ssrc-audio-level", "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"]
	},
	video : {
		codecs		: ["h264;packetization-mode=1"],
		rtx		: true,
		rtcpfbs		: [
			{ "id": "transport-cc"},
			{ "id": "ccm", "params": ["fir"]},
			{ "id": "nack"},
			{ "id": "nack", "params": ["pli"]}
		],
		extensions	: [ "http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"]
	}
};
```

**Comment by murillo128** [comment]
> I am not sure it is webrtc's bug or medooze, iOS native sdk can not talk to another client when using `framemarking` , i disable that for now.

Could be related to this
https://bugs.chromium.org/p/webrtc/issues/detail?id=10746#c2

**Comment by murillo128** [comment]
have you tried it? can we close the issue?

**Comment by murillo128** [comment]
closing for now, please reopen if needed
