### ISSUE TITLE
glibc detected *** node: free(): invalid pointer error 

### ISSUE THREAD

**Issue by kshitij199319** [medooze/media-server-node#95]
Hi @murillo128 ,
I have installed medooze-node-server on rhel 6 linux servers which have gcc 8+ configured. It installed properly. I started the medooze node server  at port 8000. When I tried to start recording, The offer is sent from the client side to the server but no response I got from the server end and no webrtc connection was established.  Instead I got error as:

*** glibc detected *** node: free(): invalid pointer: 0x00000030dc6f320 ***
I think that there may be some problem with endpoint creation. Also I have set UDP port range from min(8002) to max(9900)  . Here I attach the snapshot of the error. 
![d1](https://user-images.githubusercontent.com/46917281/61613619-711c1280-ac7f-11e9-8451-1ca6f20cdc11.png)

Kindly have a look into the issue, as I am unable to understand.

**Comment by murillo128** [comment]
Can you check with latest version?

**Comment by kshitij199319** [comment]
Hi @murillo128 
I upgraded to the latest version 0.73.0 and tried recording again, but the error occurred again.
I am working on an RHEL 6 server. 
The error is difficult to understand, therefore any help would be appreciated. 
Are there any environment restrictions for running the Media Server?
![Medooze Error](https://user-images.githubusercontent.com/46917281/64255785-b3ec2e00-cf3f-11e9-85ba-e928b550e81b.PNG)

**Comment by murillo128** [comment]
please enable core dumps `ulimit -c unlimited` and get a proper backtrace from it:
``` 
gdb node core
>bt
```

**Comment by kshitij199319** [comment]
Hi Murillo,
Sorry for the late reply... As instructed we enabled the core dumps and found the following logs after the backtrace. The error is difficult to understand, therefore any help would be appreciated.

![GDB Core Dump 0](https://user-images.githubusercontent.com/46917281/65427837-da133880-de30-11e9-939e-5d96383627b8.PNG)
![GDB Core Dump](https://user-images.githubusercontent.com/46917281/65428466-09767500-de32-11e9-9f6e-26a0d4ad4a12.PNG)

**Comment by murillo128** [comment]
does this happens also with `0.76.0` version? there was a minor change in properties handling

**Comment by kshitij199319** [comment]
Yes I tried it with the latest version 76.0.0.
No difference. Still aborts the same way.

**Comment by murillo128** [comment]
can you print the bactrace with latest version please?

**Comment by kshitij199319** [comment]
Yes sure. This time the GDB backtrace looks different. But the error occurred in the same way.
Backtrace of core dump:
![GDB Core Dump 2](https://user-images.githubusercontent.com/46917281/65485883-a7188580-dec0-11e9-9899-237386fc4dcb.PNG)


Error:
![Error](https://user-images.githubusercontent.com/46917281/65485891-b0a1ed80-dec0-11e9-8a98-0638c0c5fe35.PNG)

**Comment by murillo128** [comment]
the first bactrace is incorrect. Note the error "no executable to debug" in
gdb

**Comment by kshitij199319** [comment]
Really sorry about that. I directly ran the gdb bt.
This is the correct one:
![GDB Dump New 0](https://user-images.githubusercontent.com/46917281/65488032-c8c83b80-dec5-11e9-9d64-81e6568ecbd8.PNG)

![GDB Dump New 1](https://user-images.githubusercontent.com/46917281/65488040-ce258600-dec5-11e9-8c83-3b3ec74ceb43.PNG)

**Comment by murillo128** [comment]
the backtrace from the seg fault doesn't seem to come from the media server code, but from the node itself, which is kind of strange.

If you are able to reproduce it reliably, please enable `asan` sanetizer by uncommenting this line: 
https://github.com/medooze/media-server-node/blob/master/binding.gyp#L29

Recompile with `npm run-script build` and try to make it fail, running node preloading the asan lib

```
 LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/8/libasan.so  node index.js <X.X.X.X>
```

**Comment by murillo128** [comment]
closing it due to lack of feedback. If this is issue is still valid, please re-open it with updated info.
